### ISSUE TITLE
Wrong text color / styling for collapsed clusters on Blueprints topology

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/docs#1032]
### Expected Behavior

See the collapsed trigger node [here](https://kestra.io/blueprints/202-purge-execution-data-including-logs-metrics-and-outputs-on-a-schedule) for eg.

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by anna-geller** [comment]
seems done now - you can reopen if you still see the issue somewhere
