### ISSUE TITLE
Add a search bar to the docs page

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1036]
### Feature description

Adding a search bar at the top of the docs navigation page will be helpful to encourage people to use our awesome search instead of manually tediously browsing the docs:

![image](https://github.com/kestra-io/docs/assets/86264395/af2585ea-6db5-4a41-8789-19b338390069)

![image](https://github.com/kestra-io/docs/assets/86264395/a2bbc0f6-a87d-487b-8034-fd913ede35dd)

Figma link: TBD

**Comment by Nico-Kestra** [comment]
https://www.figma.com/file/g8Di3M1gbajOjOqp0ZrzXO/Kestra.io?type=design&node-id=7776%3A41837&mode=design&t=toSKuticj852Wh01-1
