### ISSUE TITLE
Page customers: issue with color buttons on block getting started.

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/docs#1042]
### Describe the issue

The fonts in the buttons should be in white.
<img width="1408" alt="Capture d’écran 2024-03-14 à 10 00 50" src="https://github.com/kestra-io/docs/assets/125994028/d68e27a4-39da-457d-8a22-a6e5545ba5e3">

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MartinRst** [comment]
corrected
