### ISSUE TITLE
Fix menu

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/docs#1096]
### Describe the issue

We have feedback on the visibility of the sub-menus on a black background
- Change colors background, roll over and text
<img width="862" alt="Capture d’écran 2024-03-26 à 10 19 06" src="https://github.com/kestra-io/docs/assets/125994028/395c6826-9ed7-41b0-98c3-9ea7b094b41a">
- Issue with sub-menus not closing when clicking on a category. Is it possible to close the menu when clicking on a category?

[Figma](https://www.figma.com/file/g8Di3M1gbajOjOqp0ZrzXO/Kestra.io?type=design&node-id=7305%3A11703&mode=design&t=phuXhU4Y33KhElsU-1)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MartinRst** [comment]
merged
