### ISSUE TITLE
Syntax highlighting is still missing on blueprints

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1136]
### Describe the issue

![image](https://github.com/kestra-io/docs/assets/86264395/fdfdd719-4403-4451-a1c2-536fe943ed0c)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by wrussell1999** [comment]
Seeing a similar issue with Python and Java code blocks in the docs. Let me know if this should be opened as a separate issue but assuming they are related?

<img width="888" alt="Screenshot 2024-04-10 at 13 21 40" src="https://github.com/kestra-io/docs/assets/34094921/2aeee4ec-bddd-4f0c-81cb-cb038c6b294d">


https://kestra.io/docs/workflow-components/inputs#set-inputs-when-executing-the-flow-in-python

**Comment by wrussell1999** [comment]
Resolved with https://github.com/kestra-io/docs/pull/1212
