### ISSUE TITLE
Create the Video Tutorials Page

### ISSUE THREAD

**Issue by MartinRst** [kestra-io/docs#1176]
### Issue description

Link to figma: https://www.figma.com/file/g8Di3M1gbajOjOqp0ZrzXO/Kestra.io?type=design&node-id=10486-18571&mode=design&t=JEHwsyKAw83stcaO-0

Title: All Things Kestra in Video
description: Discover all our video tutorials, hands-on video, and more.

Path: https://kestra.io/tutorial-videos

might need Strapi integration to add content on this page (like it is for the external blogs here: https://kestra.io/blogs/community

**Comment by wrussell1999** [comment]
Is this resolved now?
