### ISSUE TITLE
Won't run locally on Arm based Macs

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/docs#1185]
### Describe the issue

Website won't run locally on ARM (Apple M1, M2, M3 etc) without the following package installed. However worth checking this doesn't break on x86 machines.

- @esbuild/darwin-x64
- @rollup/rollup-darwin-x64

Example error
```
[11:10:22]  ERROR  Cannot find module @rollup/rollup-darwin-arm64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try npm i again after removing both package-lock.json and node_modules directory.
```

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by shrutimantri** [comment]
Confirmed that the website runs locally on x86_64 machines.
Attaching the screenshot showing nux running and giving 200 responses, followed by the machine architecture.

![Screenshot 2024-05-08 at 12 37 13 PM](https://github.com/kestra-io/docs/assets/6594483/67a97eca-01b6-494c-b260-b3e519f54fef)

**Comment by wrussell1999** [comment]
Reopening as this is still an issue on Arm based Macs without installing those packages.

**Comment by wrussell1999** [comment]
Seems to work if you use Node version 20 or higher. We did have to remove the `package-lock.json` in order for this to work.

 https://github.com/kestra-io/docs/commit/33816b1c7271b9bcba6e1569bfff5f942ad985c2
