### ISSUE TITLE
Fix DB2 plugin docs URL

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1192]
### Describe the issue

The link doesn't render: https://kestra.io/plugins/plugin-jdbc-db2

The same works on develop: https://develop.kestra.io/plugins/plugin-jdbc-db2

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by shrutimantri** [comment]
The link is rendering now.
