### ISSUE TITLE
Linking specific markdown headers via hashtags in a page URL doesn't work

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1193]
### Describe the issue

![image](https://github.com/kestra-io/docs/assets/86264395/f3e6939b-0961-478f-aaff-41e3eb4dbcb6)

see example https://kestra.io/blogs/2024-04-12-release-0-16#plugin-enhancements 

https://share.descript.com/view/wljRJy9ge9C

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MartinRst** [comment]
fixed in: https://github.com/kestra-io/docs/pull/1213
