### ISSUE TITLE
syntax highlight is not working on python / java

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/docs#1209]
see here as the [bottom](https://kestra.io/docs/workflow-components/inputs)
![image](https://github.com/kestra-io/docs/assets/2064609/a6f9af1f-c217-4d0f-8f95-92056ea2bc42)

**Comment by wrussell1999** [comment]
Related problem / context too https://github.com/kestra-io/docs/issues/1136

**Comment by wrussell1999** [comment]
Resolved with https://github.com/kestra-io/docs/pull/1212
