### ISSUE TITLE
Features page: Change icons

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/docs#1210]
### Describe the issue

<img width="1644" alt="Capture d’écran 2024-04-16 à 10 35 17" src="https://github.com/kestra-io/docs/assets/125994028/062a5cec-3549-46fc-a388-91f830194250">

On the features page, the icons haven't been updated in the frontend of the new website. Is it possible to do so for the next 3 blocks?
- Simple API-First Workflows as Code
- Fast Development, Painless Deployment
- Fast Development, Painless Deployment

[Figma](https://www.figma.com/file/g8Di3M1gbajOjOqp0ZrzXO/Kestra.io?type=design&node-id=6530%3A36427&mode=design&t=P2DZzGX5pXVpuRlq-1)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MartinRst** [comment]
closed in: https://github.com/kestra-io/docs/pull/1217
