### ISSUE TITLE
Improve Input Type documentation

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/docs#1220]
Improve the Input Type documentation with examples. Specifically the more complex ones, like ENUM. https://kestra.io/docs/workflow-components/inputs#input-types

**Comment by wrussell1999** [comment]
Add `defaults` for each one to show the types in the YAML example

**Comment by shrutimantri** [comment]
Most of the inputs defaults are addressed in: https://github.com/kestra-io/docs/pull/1285

Raised 2 issues:
Time inputs not accepting the defaults value: https://github.com/kestra-io/kestra/issues/3648
Duration inputs not accepting the defaults value: https://github.com/kestra-io/kestra/issues/3649
