### ISSUE TITLE
How-to Guide on validating outputs in Kestra

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/docs#1256]
### Description

Briefly discussed in Slack with a user encountering errors when passing a JSON to a webhook task as the JSON was invalid. Specifically the JSON contained outputs in it which contained the issue. Debugging was challenging so a guide on how to debug and check the JSON format would be ideal. 

Reference for helping build JSONs instead of string contact: https://kestra.io/docs/concepts/expression/02b.expression-usage

**Comment by wrussell1999** [comment]
To clarify:
- Ways to pass dynamic values into JSON and confirm that it is in the correct format
- Debug outputs and ensure they are expected values.
- Ways to ensure JSON is actually a valid format.

**Comment by anna-geller** [comment]
confusing, closing
