### ISSUE TITLE
Guide: Running workers independently

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/docs#1268]
### Description

From Slack:
> Can the Workers be run independently (on different hosts than the rest of the server components) in open source version? Is there any tutorial how to start the components separately and make them work together?

With the open souce version you can effectively start workers (in fact you can start any service) on any machine you want
Documentation to start each service : https://kestra.io/docs/administrator-guide/server-cli#worker

To configure them :
https://kestra.io/docs/administrator-guide/server-cli#configuration-files

Write a guide on this specifically

**Comment by wrussell1999** [comment]
Check if this already has enough information on. Running workers independently would be an EE feature.

**Comment by anna-geller** [comment]
within Admin Guide, let's add a how-to-style section on how to start each worker as a different service in Docker Compose + how to start a separate server e.g. in a standalone Java binary outside of that docker-compose setup

**Comment by anna-geller** [comment]
Seeing this issue https://github.com/kestra-io/kestra-ee/issues/620, perhaps we are not ready for a guide and need to do sth on the backend side. @Ben8t can you share more info?

**Comment by anna-geller** [comment]
cc @Ben8t if you can have a look -- related to the recent question from Paul, feel free to assign yourself if you could add this part to the docs

**Comment by Ben8t** [comment]
for myself https://kestra-io.slack.com/archives/C03FEC452NQ/p1726484989616309?thread_ts=1726232571.943889&cid=C03FEC452NQ
