### ISSUE TITLE
Guide: Create Outputs from a Shell Script

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/docs#1290]
### Description

Turn this Blueprint into a How-to Guide on using Shell Scripts and Outputs

https://kestra.io/blueprints/85-create-custom-outputs-from-a-shell-script

**Comment by anna-geller** [comment]
this can equivalent to https://kestra.io/docs/how-to-guides/python titled "Shell"

**Comment by shrutimantri** [comment]
This is complete with the PR: https://github.com/kestra-io/docs/pull/1569
