### ISSUE TITLE
Some plugin icons are black on dark website — find icons that work on both light and dark mode

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/docs#1294]
### Describe the issue

https://kestra.io/plugins/plugin-script-shell/tasks/scripts/io.kestra.core.tasks.scripts.bash

Icons should be in light version so they are properly visible

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by wrussell1999** [comment]
@shrutimantri 
- https://kestra.io/plugins/plugin-script-shell
- https://kestra.io/plugins/plugin-jdbc-arrow-flight
- https://kestra.io/plugins/plugin-jdbc-as400

**Comment by wrussell1999** [comment]
@shrutimantri has made a number of PRs to convert these. However, I've realised that we need these icons to work in dark and light mode as they are also used in the Kestra UI (which can be either).

Shruti's tweaks make it so they do work on a light background but not as well as a dark icon would. I've merged one but holding off with the realisation of working on both.

https://github.com/kestra-io/plugin-jdbc/pull/306
https://github.com/kestra-io/plugin-scripts/pull/146
https://github.com/kestra-io/plugin-openai/pull/26
https://github.com/kestra-io/plugin-fs/pull/126
https://github.com/kestra-io/plugin-serdes/pull/113

**Comment by brian-mulier-p** [comment]
@shrutimantri please instead do this
```
:danger: dear reminded for icon
You need to update the icon to handle black / white theme, example of wrong [one](https://raw.githubusercontent.com/kestra-io/kestra/6de50afeca9600dbf1c528f7daa5a3bf9a664e82/core/src/main/resources/icons/io.kestra.core.tasks.flows.WaitFor.svg), good [one](https://raw.githubusercontent.com/kestra-io/kestra/d28b63de0feef1ea629ce04e76987af4f6076c1d/core/src/main/resources/icons/io.kestra.core.tasks.flows.Pause.svg). The main difference is :
fill="currentColor"  
that allow to change the color of the svg.
Please take care of this?
```

**Comment by brian-mulier-p** [comment]
Can we revert the one you merged @wrussell1999

**Comment by wrussell1999** [comment]
Reverted https://github.com/kestra-io/plugin-serdes/pull/114

**Comment by anna-geller** [comment]
will be done as part of https://github.com/kestra-io/kestra/issues/4154 because we will be able to change icon colors via code (e.g. revert colors)
