### ISSUE TITLE
Installing plugins on kestra local server

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/docs#1298]
### Describe the issue

On this page https://kestra.io/docs/installation/standalone-server, I see the instructions:
```
Running the jar version will come without any plugins. You need to install them manually with the kestra plugins install directory_with_plugins/ command.
```

But the command fails with the error:
```
java.lang.IllegalArgumentException: Bad artifact coordinates plugins, expected format is <groupId>:<artifactId>[:<extension>[:<classifier>]]:<version>
```

Does this instruction need some amends?

### Environment

- Kestra Version: 0.16.4
- Operating System (OS/Docker/Kubernetes): MacOS M1
- Java Version (if you don't run kestra in Docker): 21.0.3

**Comment by shrutimantri** [comment]
![Screenshot 2024-05-06 at 12 34 31 PM](https://github.com/kestra-io/docs/assets/6594483/a3783795-831e-43b6-b2b8-e992d1cef5b8)

Screenshot showing the commands and the content of plugins folder.

**Comment by loicmathieu** [comment]
Plugins version 0.17 can only work with Kestra version 0.17
