### ISSUE TITLE
Too much free space on large screens

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1323]
### Issue description

![image](https://github.com/kestra-io/docs/assets/86264395/f6444cb8-6c74-4511-ad0c-1073b9381b57)

**Comment by anna-geller** [comment]
closing as there is no solution for now ACC. to @Nico-Kestra

**Comment by Nico-Kestra** [comment]
Content max 1140px 
<img width="1387" alt="Capture d’écran 2024-05-17 à 09 14 34" src="https://github.com/kestra-io/docs/assets/125994028/c9b66c01-58e8-424b-937a-ac070ed910c9">

**Comment by anna-geller** [comment]
seems done
