### ISSUE TITLE
Prioritize Docs on the website's search bar

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1332]
### Description

Often, the best results are not shown at the top. Feature requested by @aballiet 

Example:
![image](https://github.com/kestra-io/docs/assets/86264395/e5f4ef6d-37c7-48b8-89c2-edf68b485513)

cc @tchiotludo in case you have an idea

**Comment by Skraye** [comment]
Note that @aballiet didnt notice the bar at the bottom and suggested that we put it at the top

**Comment by tchiotludo** [comment]
we could boost some search, for now, we are not boosting any element (all type DOCS, BLUEPRINT, ...) are at the same level. 
Possibilities are : 
- Boosting when no bottom filter is selected (meaning globally we will boost DOCS) 
- Add a tag on some docs to boost them manually.

**Comment by anna-geller** [comment]
> Boosting when no bottom filter is selected (meaning globally we will boost DOCS)

this totally makes sense, let's start there and move the filter (All, Plugins, Docs, ...) to the top to make sure it's not missed.

**Comment by anna-geller** [comment]
filter position is done https://github.com/kestra-io/docs/pull/1344 

the only issue left is to prioritize Docs in the search

**Comment by anna-geller** [comment]
works now

![image](https://github.com/user-attachments/assets/13ba885b-9ae8-4efc-ad6c-cfce6ef372da)
