### ISSUE TITLE
Rename VS Code editor by Code Editor in all relevant places

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1338]
### Description

- [x] Home page
- [x] Namespace Files docs
- [x] Script task docs
- [x] Validate mentions in script plugins
- [x] Validate mentions in blueprints
- [ ] [UI Page](https://kestra.io/docs/getting-started/ui)

**Comment by anna-geller** [comment]
mainly screenshots and blueprints left after https://github.com/kestra-io/docs/commit/19c143055f3f6022fbeb03e27b8e8886a081113d

**Comment by anna-geller** [comment]
Change the visual on the homepage to 

![image](https://github.com/kestra-io/docs/assets/86264395/980b7bb0-dabf-4244-b027-cf724dc03641)

**Comment by shrutimantri** [comment]
Blueprints : ✅ (None of them have)
Screenshots:

https://github.com/kestra-io/docs/pull/1354
https://github.com/kestra-io/docs/pull/1362
https://github.com/kestra-io/docs/pull/1372
