### ISSUE TITLE
Update outdated examples to use core plugin types

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/docs#1370]
### Description

A lot of plugins types have been updated for 0.17.0 to be part of core. We need to update examples in the docs to use the new style.

For example:
`io.kestra.plugin.fs.http.request` to `io.kestra.plugin.core.http.Request`
`io.kestra.core.tasks.flows.Pause` to `io.kestra.plugin.core.flow.Pause`

**Comment by anna-geller** [comment]
to see the full list:
- https://api.develop.kestra.io/v1/plugins - those are the new plugin names
- https://api.kestra.io/v1/plugins - those are the old plugin names

**Comment by anna-geller** [comment]
@shrutimantri here is a markdown table with the old and new plugin names for the core plugins that have changed:

| Old Name                                       | New Name                                  |
|------------------------------------------------|-------------------------------------------|
| `io.kestra.core.tasks.debugs.Echo`             | `io.kestra.plugin.core.debug.Echo`        |
| `io.kestra.core.tasks.debugs.Return`           | `io.kestra.plugin.core.debug.Return`      |
| `io.kestra.core.tasks.executions.Counts`       | `io.kestra.plugin.core.execution.Count`   |
| `io.kestra.core.tasks.executions.Fail`         | `io.kestra.plugin.core.execution.Fail`    |
| `io.kestra.core.tasks.executions.Labels`       | `io.kestra.plugin.core.execution.Labels`  |
| `io.kestra.core.tasks.flows.AllowFailure`      | `io.kestra.plugin.core.flow.AllowFailure` |
| `io.kestra.core.tasks.flows.Dag`               | `io.kestra.plugin.core.flow.Dag`          |
| `io.kestra.core.tasks.flows.EachParallel`      | `io.kestra.plugin.core.flow.EachParallel` |
| `io.kestra.core.tasks.flows.EachSequential`    | `io.kestra.plugin.core.flow.EachSequential`|
| `io.kestra.core.tasks.flows.ForEachItem`       | `io.kestra.plugin.core.flow.ForEachItem`  |
| `io.kestra.core.tasks.flows.If`                | `io.kestra.plugin.core.flow.If`           |
| `io.kestra.core.tasks.flows.Parallel`          | `io.kestra.plugin.core.flow.Parallel`     |
| `io.kestra.core.tasks.flows.Pause`             | `io.kestra.plugin.core.flow.Pause`        |
| `io.kestra.core.tasks.flows.Sequential`        | `io.kestra.plugin.core.flow.Sequential`   |
| `io.kestra.core.tasks.flows.Subflow`           | `io.kestra.plugin.core.flow.Subflow`      |
| `io.kestra.core.tasks.flows.Switch`            | `io.kestra.plugin.core.flow.Switch`       |
| `io.kestra.core.tasks.flows.Template`          | `io.kestra.plugin.core.flow.Template`     |
| `io.kestra.core.tasks.flows.WorkingDirectory`  | `io.kestra.plugin.core.flow.WorkingDirectory`|
| `io.kestra.core.tasks.http.Download`           | `io.kestra.plugin.core.http.Download`     |
| `io.kestra.core.tasks.http.Request`            | `io.kestra.plugin.core.http.Request`      |
| `io.kestra.core.tasks.log.Fetch`               | `io.kestra.plugin.core.log.Fetch`         |
| `io.kestra.core.tasks.log.Log`                 | `io.kestra.plugin.core.log.Log`           |
| `io.kestra.core.tasks.states.Delete`           | `io.kestra.plugin.core.state.Delete`      |
| `io.kestra.core.tasks.states.Get`              | `io.kestra.plugin.core.state.Get`         |
| `io.kestra.core.tasks.states.Set`              | `io.kestra.plugin.core.state.Set`         |
| `io.kestra.core.tasks.storages.Concat`         | `io.kestra.plugin.core.storage.Concat`    |
| `io.kestra.core.tasks.storages.DeduplicateItems`| `io.kestra.plugin.core.storage.DeduplicateItems`|
| `io.kestra.core.tasks.storages.Delete`         | `io.kestra.plugin.core.storage.Delete`    |
| `io.kestra.core.tasks.storages.FilterItems`    | `io.kestra.plugin.core.storage.FilterItems`|
| `io.kestra.core.tasks.storages.LocalFiles`     | `io.kestra.plugin.core.storage.LocalFiles`|
| `io.kestra.core.tasks.storages.Purge`          | `io.kestra.plugin.core.storage.Purge`     |
| `io.kestra.core.tasks.storages.PurgeExecution` | `io.kestra.plugin.core.storage.PurgeExecution`|
| `io.kestra.core.tasks.storages.Reverse`        | `io.kestra.plugin.core.storage.Reverse`   |
| `io.kestra.core.tasks.storages.Size`           | `io.kestra.plugin.core.storage.Size`      |
| `io.kestra.core.tasks.storages.Split`          | `io.kestra.plugin.core.storage.Split`     |
| `io.kestra.core.tasks.templating.TemplatedTask`| `io.kestra.plugin.core.templating.TemplatedTask`|
| `io.kestra.core.tasks.trigger.Toggle`          | `io.kestra.plugin.core.trigger.Toggle`    |
| `io.kestra.core.models.triggers.types.Webhook` | `io.kestra.plugin.core.trigger.Webhook`   |
| `io.kestra.core.models.triggers.types.Schedule`| `io.kestra.plugin.core.trigger.Schedule`  |
| `io.kestra.core.models.triggers.types.Flow`    | `io.kestra.plugin.core.trigger.Flow`      |
| `io.kestra.core.models.tasks.runners.types.ProcessTaskRunner` | `io.kestra.plugin.core.runner.Process` |

**Comment by anna-geller** [comment]
@shrutimantri on develop docs, we also need to rename all mentions of taskDefaults to pluginDefaults -- it's a simple rename we did

**Comment by anna-geller** [comment]
done in https://github.com/kestra-io/docs/pull/1385
