### ISSUE TITLE
Git PushFlows not working

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/docs#1371]
### Describe the issue

I am following the How-to Guide as mentioned here: https://kestra.io/docs/how-to-guides/pushflows
On executing the flow with PushFlow task (with dryrun), I see no changes.
I was expecting to see the changes related to addition of the new flow (as shown in the video). Here is a screenshot of the output.
<img width="1463" alt="Screenshot 2024-05-20 at 5 38 33 PM" src="https://github.com/kestra-io/docs/assets/6594483/57589048-c32b-4e5b-b3b8-ace36ce0f094">

### Environment

- Kestra Version: 0.17.0
- Operating System (OS/Docker/Kubernetes): Docker
- Java Version (if you don't run kestra in Docker):

**Comment by wrussell1999** [comment]
Shruti and I looked at this together. The secret was definitely present inside of Kestra (using a Log task) but the flow had an auth issue. GitHub said the token was never used when we checked too.

**Comment by brian-mulier-p** [comment]
Solved by https://github.com/kestra-io/plugin-git/commit/c0e7fb36bee3c313eb72ae38063362cdaa7086a8
