### ISSUE TITLE
Add a link/mention from Triggers to Realtime Triggers and vice versa

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1416]
### Description

For each `Trigger` that has a corresponding `RealtimeTrigger` alternative, mention it in the `description`.

The same in reverse: 
For each `RealtimeTrigger` that has a corresponding `Trigger` alternative, mention it in the `description`.

The goal is to cross-link them to make it easy for the user to choose the right trigger type for their use case (whether to process events in real-time or in batch).

Example: https://github.com/kestra-io/plugin-kafka/commit/d95b4592ee446e97b7a435f9c83ab93a91b9711d 

We will need a similar commit for all `RealtimeTrigger` plugins.

**Comment by shrutimantri** [comment]
This is now complete.
