### ISSUE TITLE
Remove Local IDE tab from Overview page

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/docs#1440]
### Describe the issue

The overview page: https://kestra.io/overview contains Local IDE tab describing the Editor tab which we had prior to v0.17.0
We should remove this tab from the page.

![Screenshot 2024-06-05 at 9 52 10 AM](https://github.com/kestra-io/docs/assets/6594483/f2bb4637-67ce-42fd-8f0f-7633d1b8eef7)

### Environment

- Kestra Version: 0.17.0
- Operating System (OS/Docker/Kubernetes): N/A
- Java Version (if you don't run kestra in Docker): N/A

**Comment by anna-geller** [comment]
looks correct now 

![image](https://github.com/user-attachments/assets/db62c628-9174-46c3-bacb-694ff35b0d0f)
