### ISSUE TITLE
Adjust blueprints and documentation examples so that we don't use deprecated LocalFiles and outputDir 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1442]
### Description

Example blueprint that needs to be modified to use inputFiles instead of LocalFiles task: https://kestra.io/blueprints/106-run-dbt-cli-commands-in-one-container:-dbt-deps-and-dbt-build

Check this section for more details https://kestra.io/blogs/2024-06-04-release-0-17#deprecations

**Comment by shrutimantri** [comment]
All the examples with LocalFiles in documentation and blueprints are checked, and the LocalFiles task has been removed.
Blueprints impacted: 84, 87, 88, 106, 107, 113, 117, 140, 141, 142, 152
