### ISSUE TITLE
Update the Demo page

### ISSUE THREAD

**Issue by MartinRst** [kestra-io/docs#1473]
### Issue description

for the page: 

Kestra.io/demo, update the design for this one: https://www.figma.com/design/g8Di3M1gbajOjOqp0ZrzXO/02_Kestra.io?node-id=11729-24755&t=3wVxgUigDOea3bGy-1

Note: the logo for the companies are Fixed and in two lines.

**Comment by Ayush9026** [comment]
@MartinRst sir i will solve this issue.
