### ISSUE TITLE
Anchor link are hidden by menu 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/docs#1486]
when you click on some [link with anchor](https://kestra.io/plugins/core/triggers/trigger/io.kestra.plugin.core.trigger.schedule#recovermissedschedules), the anchor will scroll till the top of the page and not allowing to see the content (hidden by menu) 
![image](https://github.com/kestra-io/docs/assets/2064609/d7cb5cc7-f822-4cb0-884f-cfe766b18616)

we need to scroll taking the top menu height, final render must be: 
![image](https://github.com/kestra-io/docs/assets/2064609/92c5b61b-9af9-45a2-8663-7b5a1d5fdc3b)

**Comment by MartinRst** [comment]
Merged in: https://github.com/kestra-io/docs/pull/1489
