### ISSUE TITLE
Wrong display of the Cassandra plugin on the website - it should show Cassandra and AstraDB separately

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1499]
### Describe the issue

![image](https://github.com/kestra-io/docs/assets/86264395/890e6c37-7bf2-4b84-800a-6f5894fd37ad)

**Comment by brian-mulier-p** [comment]
Should be fixed by https://github.com/kestra-io/plugin-cassandra/commit/78a268f6742d7bd9c0142d0dfcc12be067216336 that got released in the Cassandra plugin v0.17.1 that will be included in Kestra v0.17.7.

We should rollout the API after the release has been done.

**Comment by brian-mulier-p** [comment]
Confirm it's fixed 
![image](https://github.com/kestra-io/docs/assets/37618489/5582f5dd-a089-4dea-b4e9-dc973560e025)
