### ISSUE TITLE
Improve docs that got negative feedback

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1500]
### Description

Evaluate and improve the following docs pages by clarifying the concepts, fixing any typos/grammar and adding more examples:
- [x] https://kestra.io/plugins/core/conditions/io.kestra.plugin.core.condition.datetimebetweencondition
- [x] https://kestra.io/docs/concepts/expression/filter/temporal#dateadd 
- [x] https://kestra.io/plugins/plugin-jdbc-druid/tasks/io.kestra.plugin.jdbc.druid.query -- here the example is bad since Druid is meant for OLAP, instead of `fetchOne` (fetch 1 row), the example should use `store: true`. Also title: "Query a Apache Druid database." --> "Query an Apache Druid database."
- [x] provide more examples here https://kestra.io/docs/concepts/expression/filter/json 
- [x] clarify this policy + give specific examples of when to use which option https://kestra.io/plugins/plugin-nats/tasks/io.kestra.plugin.nats.consume#deliverpolicy 
- [x] provide more examples https://kestra.io/docs/concepts/expression/filter/json

**Comment by shrutimantri** [comment]
All the docs are fixed.
