### ISSUE TITLE
Screenshots with the old vscode Editor item and editor menu item on Overview Page need updating

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/docs#1514]
### Description

A couple of images with the Editor visible in the screenshots on the overview page.

https://kestra.io/overview

The ones with screenshots of the vscode editor itself: 
- Local IDE
- Stay Organized with Namespaces

![Screenshot 2024-06-28 at 16 45 58](https://github.com/kestra-io/docs/assets/34094921/e642d86e-63f7-4a29-aebe-e43e3578cc9e)
![Screenshot 2024-06-28 at 16 46 06](https://github.com/kestra-io/docs/assets/34094921/eb415fe0-ff7b-406f-b22d-4f0ba85754e1)
![Screenshot 2024-06-28 at 16 46 17](https://github.com/kestra-io/docs/assets/34094921/9e92cb68-b59c-42ff-abf8-7e0be7211588)

**Comment by shrutimantri** [comment]
The screenshots have been provided to @wrussell1999  and @MartinRst.
The screenshots need to be converted from png to svg, and then uploaded onto the website.
