### ISSUE TITLE
Create a How-To guide section: ETL Pipelines in Kestra

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1534]
### Description

Create a How-To guide page explaining how kestra supports ETL use cases. 

This page should include:
- [x] **dbt:** a short but complete example extracting data e.g. extract CSV/parquet files using HTTP Download task + then Transform and Load using dbt
- [ ] **SQLMesh + Dataform** — mention possibilities to implement similar patterns to dbt with https://kestra.io/plugins/plugin-sqlmesh and https://kestra.io/plugins/plugin-dataform
- [x] **DuckDB**: example showing how data can be transformed via SQL directly — mention that there are similar query tasks for almost any database like Snowflake, Postgres
- [x] **Spark + Databricks**: show how Big Data jobs can be submitted to a Spark cluster
- [x] **Python**: show how to transform data just using a Python script
- [x] **Batch task runners**: show how compute- and memory-intensive Python scripts can be scaled by easily changing a single property to offload that data processing to remote Batch compute resources + point to task runner docs to read more
- [ ] (optionally) mention internal storage and ION data format used by kestra to standardize ETL and data processing across systems — this standardized format allows to extract data from any system and process it in the same way. For example, today you might be using Snowflake and in the future you might be using BigQuery — simply swap Snowflake for BigQuery task and the downstream processes are unaffected due to that standardized format.

**Comment by Ayush9026** [comment]
@anna-geller mam i will solve this issue.
