### ISSUE TITLE
Kestra's homepage needs screenshot correction

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/docs#1536]
### Describe the issue

Some of the screenshots on Kestra's homepage http://kestra.io needs correction.

This one needs updated plugin names, and namespace can be corrected to `company.team`: 
![Screenshot 2024-07-07 at 7 46 31 PM](https://github.com/kestra-io/docs/assets/6594483/3510d2c3-16fe-48b1-b8e3-5a6ca6bb6500)

This one needs correction as `id` is appearing twice at the top, and namespace can be corrected to `company.team`:
![Screenshot 2024-07-07 at 7 47 52 PM](https://github.com/kestra-io/docs/assets/6594483/3e2e6d86-832c-4cd6-b53f-2983777ffd1c)

Namespace can be corrected to `company.team` here:
![Screenshot 2024-07-07 at 7 49 22 PM](https://github.com/kestra-io/docs/assets/6594483/8f18b594-3eb7-44d4-a79a-ae396b78eb04)

### Environment

- Kestra Version: N/A
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by Nico-Kestra** [comment]
@anna-geller ok for you? [
Figma](https://www.figma.com/design/g8Di3M1gbajOjOqp0ZrzXO/02_Kestra.io?node-id=10976-24121&t=AW0IgU53xYw5L2PV-1)
