### ISSUE TITLE
Plugin subgroups like S3, BigQuery, Slack or Discord should show up with their own icon rather than the parent plugin's icon

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1542]
### Description

Search for any plugin from a subgroup like S3, BigQuery, or Slack and you will see that the website shows only the parent plugin. In the example below, when searching for S3, it should show the S3 plugin with the S3 logo https://kestra.io/plugins/plugin-aws#s3 

![image](https://github.com/kestra-io/docs/assets/86264395/21bc95cc-bba7-4415-bdcd-65dd5762ec07)

**Comment by t-chatoyan** [comment]
https://github.com/kestra-io/docs/pull/1559
