### ISSUE TITLE
Document how to return data from the Executions API endpoint to trigger a flow from anywhere and consume the outputs

### ISSUE THREAD

**Issue by aku** [kestra-io/docs#1545]
### Feature description

Currently webhook returns some metadata about a workflow but you can not wait for the workflow to finish and return some outputs.

It would be very convenient to be able to create APIs on top of Kestra to do some work and return result in the same request. I.e. introduce synchronous API.

**Comment by aku** [comment]
Hi @anna-geller I did not realize there was a separate API. What about security? Can I provide some API token to safely call this API? In case of webhook I was able to use custom ID as a token

**Comment by anna-geller** [comment]
You can provide an API token in the Enterprise Edition. In the OSS version, you can protect your instance with basic auth and then you would need to add the username and password to the request headers IIRC

**Comment by aku** [comment]
> You can provide an API token in the Enterprise Edition. In the OSS version, you can protect your instance with basic auth and then you would need to add the username and password to the request headers IIRC

ok, I see. In OSS edition I will have to solve it on proxy level
