### ISSUE TITLE
Improve the configuration guide

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1546]
### Description

Kestra is highly configurable. As a result, there's a lot you can configure, to the extent that the Configuration docs page has become overwhelmingly complex. 

We should explore some friendlier designs for configuration to consolidate configuration per product/service/user journey step e.g. 
1. **Initial Setup** — all configuration pages that are only required during the first setup, like configuring DB and storage backend, secrets
2. **Feature Flags** e.g. enabling specific features or keeping deprecated features
3. **Governance** — Variables, Plugins, Usage (telemetry) etc = things that can be changed anytime

@wrussell1999 I'm aware this would mean adding nesting 😢 but seeing where we are already (there will be more configuration in the future!), breaking this down seems inevitable.

**Comment by wrussell1999** [comment]
I think nesting is a positive thing here. There's a point where it makes sense and we're at that point now!

**Comment by shrutimantri** [comment]
@anna-geller Can you take a look at this hierarchy? Does this look good?
Configuration Guide
  - Initial Setup
      - Configuration Setup 
      - Database
      - Storage
      - Server
      - URL
  - Enterprise Edition
      - Enterprise Edition
      - Elasticsearch
      - Kafka
  - Feature Flags
      - Enabled
      - Encryption
      - Environment
      - Tutorial Flows
      - Webserver
  - Governance
       - API Retries
       - Endpoints
       - JVM
       - Logging
       - Metrics
       - Micronaut
       - Plugins
       - System Flows
       - Tasks
       - Usage
       - Variables

**Comment by anna-geller** [comment]
thx Shruti, I'll let @wrussell1999 validate this sometime later this month. I think the "lift-and-shift" approach may not be enough, I think we need to reevaluate the information architecture here entirely e.g.:
- System Flows, JVM, Endpoints and Metrics pages are too small for their own pages
- Storage is already explained in Configuration Setup and can potentially be moved there to have all info in one place
- Proxy configuration defined in URL can be moved to Micronaut as it's purely micronaut setting
- Tasks and Plugins can likely be combined into one as they talk about the same mostly
- API Retries and Logging are super technical, they don't fit into Governance.

We can let Will create a new version in a separate branch with deployment preview link 👍 Will can validate with a developer e.g. Loic to check if new structure makes sense

**Comment by wrussell1999** [comment]
- Combine to one page as a reference
- Pages with more in-depth guides be split to reference and how-to guides/admin guides
- Rename as configuration reference

**Comment by wrussell1999** [comment]
Also looking at moving the Server CLI page into the reference docs for easier finding

REFERENCE DOCS
Configuration
Open Source API
Cloud & Enterprise Edition API
Server CLI

**Comment by wrussell1999** [comment]
Solved https://github.com/kestra-io/docs/pull/1878
