### ISSUE TITLE
Keep original size of the images instead of stretching them to the full width 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1565]
### Description

Look at that gigantic Google Cloud logo :) we should keep the original image size without stretching it to the full width of the screen 

https://kestra.io/docs/concepts/task-runners/types/google-batch-task-runner

![image](https://github.com/user-attachments/assets/b1ba5037-299c-49d1-a5ae-ee721b2bd30a)

**Comment by t-chatoyan** [comment]
https://github.com/kestra-io/docs/pull/1567
