### ISSUE TITLE
New hero for the Kestra Homepage

### ISSUE THREAD

**Issue by MartinRst** [kestra-io/docs#1570]
### Issue description

Hello! 

We have a new hero for the Kestra homepage that you can find here:  https://www.figma.com/design/g8Di3M1gbajOjOqp0ZrzXO/02_Kestra.io?node-id=12437-33205&t=jij4oFZFDVhnVCJP-1

The hero change and the listing of the customers are now in 2 line statics.

We have an animation on the first word: Orchestrate, Schedule, Automate 

<img width="858" alt="image" src="https://github.com/user-attachments/assets/7eb16269-9378-40d5-b162-f9709351516b">

**Comment by anna-geller** [comment]
Martin said it's done
