### ISSUE TITLE
Remove LocalFiles-based examples from documentation

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/docs#1571]
### Description

The LocalFiles plugin is deprecated, documentation should be updated to match our suggestions in the migration guide. 

For instance
https://kestra.io/plugins/plugin-ansible/tasks/cli/io.kestra.plugin.ansible.cli.ansiblecli

**Comment by shrutimantri** [comment]
This is already corrected in the develop branch: https://develop.kestra.io/plugins/plugin-ansible/tasks/cli/io.kestra.plugin.ansible.cli.ansiblecli
