### ISSUE TITLE
Update outdated Code Editor UI screenshots on the website

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1585]
change both images to the latest version of our custom editor: https://kestra.io/overview
![image](https://github.com/user-attachments/assets/54370d8f-a1a7-4e4e-b96c-54d0fbf7d20c)

![image](https://github.com/user-attachments/assets/a89b2c60-37d3-4bd5-8bbc-d3b2e83de6ed)

also change this to the new Namespace Overview (best create a new tenant with plausible namespace names):

![image](https://github.com/user-attachments/assets/db642ed2-d7f5-4ea5-b0fa-affa1b548f00)

replace with sensible namespace names and structure:
![image](https://github.com/user-attachments/assets/9ca7d390-9204-4ac2-ae72-31b9d56b73eb)

**Comment by shrutimantri** [comment]
I have the png versions of the updated screesnhots.
how do we get the svg versions of the same? (the online tools are not that great at the job)
<img width="1728" alt="Screenshot 2024-07-25 at 4 01 28 PM" src="https://github.com/user-attachments/assets/0d5a8fb1-e62d-4f8a-9f40-86e7f948a31d">
<img width="1728" alt="Screenshot 2024-07-25 at 1 57 08 PM" src="https://github.com/user-attachments/assets/a184a93f-b651-41fa-bc71-1e0536217ade">
<img width="1728" alt="Screenshot 2024-07-25 at 1 56 18 PM" src="https://github.com/user-attachments/assets/83bb227a-7352-41c1-bec2-c33f26386b38">
