### ISSUE TITLE
Add support to render mermaid diagrams in the docs when using mermaid code snippets

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1586]
### Issue description

it would be great to render mermaid code snippets as this one:
![image](https://github.com/user-attachments/assets/11a053c8-0ec0-47c6-9f8c-e54c5a2cd5fd)
![image](https://github.com/user-attachments/assets/37eec789-684a-416f-b5f2-e7117c5e9b60)

GitHub-flavored markdown supports it by default.

See https://github.com/mermaid-js/mermaid 

Example mermaid code you can test it with:

```mermaid
flowchart TD
    A[Namespaces] -->|optionally restrict Permissions| B[Access Binding]
    B -->|grants Permissions| C[User]
    B -->|grants Permissions| D[Group]
    B -->|grants Permissions| E[Service Account]
    F[Roles] -->|define Permissions| B

    C -->|can be Owner or Member| D
    E -->|can be Owner or Member| D
```

**Comment by t-chatoyan** [comment]
https://github.com/kestra-io/docs/pull/1587
