### ISSUE TITLE
Plugins tags and bullet points on Careers pages don't render correctly 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1612]
### Describe the issue

We have some issues currently on the website. 

There are two issues specifically:
1) The tags don't render correctly on https://kestra.io/plugins. I tried three browsers: Brave, Chrome and  Arc. So far, after clearing the cache, only Chrome displays plugins correctly. Brave and Arc display it correctly only in a private window. 

![image](https://github.com/user-attachments/assets/3bc915f3-6d81-45ce-bee1-38ee00556d1c)

should be:

![image](https://github.com/user-attachments/assets/af7e74ec-197b-488c-8ccb-63355cc9988f)

2) Bullet points seem to be gone on Careers pages e.g. https://kestra.io/careers/technical-writer. Also here, in a private browser window it looks OK, but normally, the issue is visible. 

![image](https://github.com/user-attachments/assets/d8d732d6-c5ad-4545-9c91-790c8a2d2b10)

should be:

![image](https://github.com/user-attachments/assets/096491d7-daeb-4dd6-8e4d-3a19ae219aff)

## Solution

perhaps check library dependencies -- it might be that one of the recently merged libraries causes some elements to not render as they used to previously 

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by Ayush9026** [comment]
@anna-geller mam i will solve this issue.
