### ISSUE TITLE
Add docs about custom functions/filters + how they differ from macros

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1642]
### Description

In general:
- macro is for simple use case, especially for users who don't know Java
- for more complex use cases + if you know Java, the custom function provides a clean interface to define some reusable functions - e.g., a user could want to create custom function for data anonymization compliant to some policy, or want to create a function to call a SaaS url shortener, etc.

Follow up to https://github.com/kestra-io/kestra/pull/4645

**Comment by jayg2309** [comment]
@anna-geller I would like to work on this

Also can you please tell under which section in the docs should I place this?

**Comment by anna-geller** [comment]
so sorry, this issue is no longer relevant as the PR was closed - feel free to check [one of these issues](https://github.com/search?q=org%3Akestra-io+label%3A%22good+first+issue%22+is%3Aopen&type=issues&utm_source=GitHub&utm_medium=github&utm_campaign=hacktoberfest2024&utm_content=Good+First+Issues )

**Comment by jayg2309** [comment]
Okay. Will have a look :)
