### ISSUE TITLE
Add examples for skipping executions

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/docs#1648]
### Description

Add examples for skipping all executions of a:
- flow (`--skip-flows`)
- namespace (`--skip-namespaces`)
- tenant (`--skip-tenents`)

Existing docs where an execution can be skipped: https://kestra.io/docs/administrator-guide/troubleshooting#unprocessable-execution

**Comment by jayg2309** [comment]
@wrussell1999 hey can you assign this issue to me?
I'll be glad to solve it

**Comment by Ben8t** [comment]
@jayg2309 let's go for it 🚀

**Comment by jayg2309** [comment]
I've generated a pull request #1826 . 
Please review it and let me know if any changes required.
@Ben8t

**Comment by Ben8t** [comment]
Thanks @jayg2309 🎉
