### ISSUE TITLE
Google Indexing of dev domain should be disabled

### ISSUE THREAD

**Issue by nicoallgood** [kestra-io/docs#1661]
### Describe the issue

Google is currently [indexing develop.kestra.io](https://www.google.com/search?client=safari&rls=en&q=site%3Adevelop.kestra.io&ie=UTF-8&oe=UTF-8) . This is not intended and can only lead to negative side-effects (duplicate content, Google confused etc.).

A dedicated https://develop.kestra.io/robots.txt should be enough :
```
# Disallow all
User-agent: *
Disallow: /
```

Since we seem to be using Nuxt, their [guidelines](https://nuxtseo.com/robots/getting-started/installation#staging-testing-environments) might be helpful:
> If you're using Preview / Staging / Testing environments you will need to implement extra configuration. **This is important to avoid duplicate content issues and these environments appearing in Google searches.**
Please read the [Disabling Indexing](https://nuxtseo.com/robots/guides/disable-indexing) guide for more information.

**Comment by tchiotludo** [comment]
done in https://github.com/kestra-io/docs/commit/4d7cfb8cb470abd0e9f0863d967b0bc31b17a03b
