### ISSUE TITLE
Create a comprehensive documentation section with subfolders explaining every part of the UI (with `editions: ["EE"]` frontmatter for EE-only pages)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1676]
### Description

[The single-page UI section](https://kestra.io/docs/getting-started/ui) is no longer sufficient. The UI has grown significantly, and some UI sections would benefit from more detailed documentation.

We can create a dedicated UI section explaining every UI page (with screenshots) with multiple structured subsections.

Some pages which are currently missing and we'll need to add:
- [x] section explaining the `Dependencies` tab on the Flow's and Namespace page and the difference between them -- explain that it shows relationships between flows created both via subflows and Flow triggers
- [x] dedicated section for all `Namespace` tabs, including the EE-only ones -- we may move some EE docs pages to the relevant UI section page instead e.g. https://kestra.io/docs/enterprise/secrets can be explained based on walking through Namespace UI in EE + showing how this differs from OSS 
- [x] some of those could benefit from videos to explain e.g. how to add Secrets or Variables in EE (and how to configure a Secrets manager e.g. with Postgres backend)

**Comment by wrussell1999** [comment]
Secrets Explainer video is already planned - will add to these pages once live

**Comment by wrussell1999** [comment]
Main migration done. We can continue decide how we want to split Enterprise pages (UI or under Enterprise) separately: https://github.com/kestra-io/docs/pull/1677
