### ISSUE TITLE
State Store is deprecated in favor of KV Store — adjust docs and plugins

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1686]
### Description

- [x] we should add a migration guide -- mostly done here https://github.com/kestra-io/docs/pull/1685
- [x] remove any mention of the State Store e.g. here we should mention KV Store tasks instead of State store https://kestra.io/docs/tutorial/fundamentals#state-store 
- [x] check any docs that mention state store
- [ ] check plugin example and their docs for singer, debezium and cloudquery to make sure they don't mention state store anymore

**Comment by shrutimantri** [comment]
@anna-geller Made changes at all places except this one: https://kestra.io/docs/enterprise/cli#kestra-sys-ee-restore-flow-listeners
I am not completely sure if it is ok to replace here.

<img width="1473" alt="Screenshot 2024-09-07 at 3 11 30 PM" src="https://github.com/user-attachments/assets/6cd26fe0-fbb5-4164-8854-054de4a9d499">
