### ISSUE TITLE
Document EE features

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/docs#169]
### Feature description

The enterprise edition is not well covered inside our documentation.
We should document it.
There is two options:
- Add a dedicated section
- Document it inside the existing documentation

My preference goes to document it inside the current documentation:
- Secrets usage must be documented inside the developer guide
- Secret configuration must be documented inside the Administrator guide
- Auth configuration must be documented inside the Administrator guide
- Audit Log must be documented inside the UI documentation
- Namespace configuration must be documented inside the UI documentation
- User management must be documented inside the Administrator guide and the UI documentation (or a link to it)

**Comment by anna-geller** [comment]
https://kestra.io/docs/kestra-editions/enterprise

follow up broken down https://www.notion.so/kestra-io/Fill-the-gaps-in-docs-62b3d287d8c94a90a0127111fc46d4d5?pvs=4
