### ISSUE TITLE
Fix the SCIM diagram in dark mode

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1693]
### Description

@Nico-Kestra can you help fix this diagram? we created this when you were OOO and you can see how much we missed you :) https://share.descript.com/view/2atlWa2ZH5e 

https://kestra.io/docs/enterprise/scim

**Comment by Nico-Kestra** [comment]
![SCIM Directory sync visual](https://github.com/user-attachments/assets/c9d313ab-8d58-44ae-a6e7-1b817ed0a767)

**Comment by anna-geller** [comment]
do you have a figma link? 

just having it on a white background is sth I already can take as a screenshot but I thought it would be cool to have a real version for a dark mode website with the arrows being white etc

**Comment by anna-geller** [comment]
done 
![image](https://github.com/user-attachments/assets/dd5b08e3-6b90-47a6-a14f-498226d77df1)
