### ISSUE TITLE
Version upgrade documentation

### ISSUE THREAD

**Issue by quentin-py** [kestra-io/docs#172]
## Context

As a Kestra administrator, I'm willing to migrate to the latest versions in order to always keep up to date.

## Related Questions
- how do I migrate from a v.0.x to a v.0.xx?
- how breaking changes are identified?
- where can I find the release change note?
- how can I stick to a precise version?

## Suggested Section
https://kestra.io/docs/administrator-guide/

**Comment by anna-geller** [comment]
done https://kestra.io/docs/administrator-guide/upgrades
