### ISSUE TITLE
Document how to add custom plugins

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/docs#173]
### Feature description

- By building your own image
- By binding a custom plugin path to the docker container
- By adding it to the KESTRA_PLUGINS dir if not using Docker

See https://kestra-io.slack.com/archives/C03FQKXRK3K/p1680859923161429

**Comment by tchiotludo** [comment]
duplicate by https://github.com/kestra-io/kestra/issues/1339

**Comment by tchiotludo** [comment]
duplicate by https://github.com/kestra-io/kestra.io/issues/250

**Comment by anna-geller** [comment]
including in bigger docs planning for easier prioritization https://www.notion.so/kestra-io/Desired-documentation-enhancements-1369a3ded29c4c8d906950cd4ac8d59e?pvs=4
