### ISSUE TITLE
MongoDB Blueprint doesn't work (reported by a job candidate)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1734]
### Issue description

This blueprint https://kestra.io/blueprints/ingest/14-write-data-in-mongodb

**Comment by shrutimantri** [comment]
This is working as expected. What is the issue here?

![Screenshot 2024-09-18 at 8 35 30 AM](https://github.com/user-attachments/assets/ab1ed4b2-9de8-4f37-b04d-f0e3ab327a10)

**Comment by Ben8t** [comment]
Yes, MongoDB tasks are working on my side too (Realtimetrigger, Find, Update).
Closing for now - @anna-geller do not hesitate to ask the candidate for more details
