### ISSUE TITLE
Improve documentation layout

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/docs#179]
### Feature description

Currently documentation layout is separated on three column:
- left nav
- content
- right nav with contribute links

The content is small and the right nav is usually not very used.

It would be great to expand the content to the place that is currently used by the right nav and to display the right nav "out" of the layout if the screen is large enough (like the slack button that stick to the right).
This would allow more content on the doc to be displayed on a single line, which is important for code block that often have a slider.

![image](https://user-images.githubusercontent.com/1819009/233027961-f914b6ab-f368-4542-a0e8-ee1418cf4925.png)

**Comment by anna-geller** [comment]
closing at it has been recently implemented 

![image](https://github.com/kestra-io/docs/assets/86264395/b8e08d5b-d0bc-42fe-a257-799fd6bb87ec)
