### ISSUE TITLE
CardLogos Component doesn't display in In-App Docs

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/docs#1808]
### Describe the issue

On this [page](https://kestra.io/docs/enterprise/kestra-identity)
<img width="1323" alt="Capture d’écran 2024-10-02 à 10 30 29" src="https://github.com/user-attachments/assets/f9291f1b-1678-4f27-887a-104eda670d99">

- The first visual doesn't take up the full width.
- The timeline is very small and should also take up the full width.
- The 3 visuals of logos are distorted.

Additionally, these 3 visuals don't appear in the UI. issue with format? 
<img width="1408" alt="Capture d’écran 2024-10-02 à 10 33 34" src="https://github.com/user-attachments/assets/af4b6656-ac2c-49c6-b3b8-bcdb94f11925">

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
Taron forgot to add "closes" https://github.com/kestra-io/docs/pull/1810

**Comment by wrussell1999** [comment]
Still broken in EE, believe it's because it uses a component rather than a link to display the photos? https://github.com/kestra-io/docs/blob/main/content/docs/06.enterprise/kestra-identity.md?plain=1

```
## Logo

::CardLogos
::
```

![Screenshot 2024-10-11 at 12 29 44](https://github.com/user-attachments/assets/6ab129bb-bee6-456a-9de1-4fa766fb581a)

**Comment by wrussell1999** [comment]
Doesn't work on:
- `latest`
- `develop`
- `develop-ee`

**Comment by brian-mulier-p** [comment]
My bad I put a wrong URL :) Fixed now
![image](https://github.com/user-attachments/assets/ad567b1e-5434-4586-9d24-69e7e470102f)
