### ISSUE TITLE
Wrap longer code blocks to the next line

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1816]
### Issue description

In some code blocks like e.g. here https://kestra.io/docs/getting-started/quickstart#start-kestra, instead of showing a slider:

![image](https://github.com/user-attachments/assets/adf44e7e-ac58-474c-8a14-4c79ab1d6c47)

it would be better to wrap long text into the new line automatically.

Ideally this way, the slider should no longer be needed.

This is especially important for mobile as there almost all code blocks have this slider:

![image](https://github.com/user-attachments/assets/1917ed16-93d9-4439-a29f-bd252687623c)

**Comment by shrutimantri** [comment]
@anna-geller What is the character limit that we should go with?

**Comment by anna-geller** [comment]
done in https://github.com/kestra-io/docs/pull/1823
