### ISSUE TITLE
Show related blueprints on use case pages

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/docs#1817]
### Issue description

On the use case pages, it shows random blueprints. Would be good to select specific ones related to the use-case.
- https://kestra.io/use-cases/software-engineers
- https://kestra.io/use-cases/data-engineers
- https://kestra.io/use-cases/platform-engineers

**Comment by Vivek-1102** [comment]
@wrussell1999 Happy to contribute can you please elaborate more about this issue?

**Comment by wrussell1999** [comment]
At the moment, when you scroll down to the blueprints section, it shows what I think is the most recent blueprints created.

![Screenshot 2024-10-08 at 18 15 39](https://github.com/user-attachments/assets/0a08ce73-128e-4bc3-8a6e-80419a683d96)

What I would like to do is show specific ones here, maybe by providing IDs for specific blueprints. E.g. 

For data engineering, these would be good:
- https://kestra.io/blueprints/Getting-Started/223-getting-started-with-kestra-a-data-engineering-pipeline-example
- https://kestra.io/blueprints/getting-started/221-getting-started-with-kestra-a-data-warehouse-and-analytics-workflow-example

For Software Engineer:
- https://kestra.io/blueprints/Getting-Started/217-getting-started-with-kestra-a-file-processing-workflow-example
(I'll find more examples for this)

For Platform Engineers:
- https://kestra.io/blueprints/Getting-Started/219-getting-started-with-kestra-an-infrastructure-automation-workflow-example
- https://kestra.io/blueprints/Getting-Started/222-getting-started-with-kestra-a-microservices-and-apis-workflow-example

**Comment by Vivek-1102** [comment]
So we need to mention the above classified blueprints with respect to their pages ?

**Comment by Vivek-1102** [comment]
@wrussell1999 can you please assign me this issue

**Comment by Vivek-1102** [comment]
while fetching the blueprints from 
https://api.kestra.io/v1/blueprints 
I got an array of 25 blueprints starting from id: 238 to id: 262 , I cannot find blueprints with the id : 219, 222, 217, 221, 223

**Comment by wrussell1999** [comment]
Hey @Vivek-1102 we may need to find someone in the internal team to look into this.

**Comment by Vivek-1102** [comment]
@wrussell1999 alright 
we don't have hacktoberfest issues here?

**Comment by wrussell1999** [comment]
@Vivek-1102 we've added the hacktoberfest topic now. We just got a new issue #1844 you could look into if you're looking for new issues

**Comment by wrussell1999** [comment]
Solved by https://github.com/kestra-io/docs/pull/1861
