### ISSUE TITLE
Healthcare and Automotive Industries page background goes to purple when refreshed

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/docs#1818]
### Describe the issue

https://kestra.io/use-cases/healthcare

https://github.com/user-attachments/assets/6f979e63-13fd-4d36-9f06-1331195cc4df

https://kestra.io/use-cases/automotive

https://github.com/user-attachments/assets/0b774150-5ba5-4bcd-9536-9538a6d10eaa

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by Vivek-1102** [comment]
I also noticed that, we want the page should be persistent with its background colour.

**Comment by Vivek-1102** [comment]
@wrussell1999 anyone working on this?

**Comment by wrussell1999** [comment]
@Vivek-1102 yes this is already assigned to @t-chatoyan

**Comment by Vivek-1102** [comment]
cool
