### ISSUE TITLE
Font size and weight different between Retail and Healthcare/Automotive Industry pages

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/docs#1821]
### Describe the issue

https://kestra.io/use-cases/retail has a lighter font weight and smaller size:
![Screenshot 2024-10-07 at 14 48 06](https://github.com/user-attachments/assets/9684271f-1436-4c6e-ac3b-b9dbb2db143b)

https://kestra.io/use-cases/healthcare has a bolder and larger font. Please adjust the retail page to match for consistency.
![Screenshot 2024-10-07 at 14 48 14](https://github.com/user-attachments/assets/b7a85947-ebc7-45af-b484-9db3f5ad4ee7)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by Vivek-1102** [comment]
This will do?
![image](https://github.com/user-attachments/assets/5f040884-1740-4cd5-94d4-2cfb8aea5d98)

**Comment by wrussell1999** [comment]
@Vivek-1102 looks good. Can you also make the "Retail Ecosystem" the same font weight as the rest?

**Comment by Vivek-1102** [comment]
Yeah sure

**Comment by Vivek-1102** [comment]
Can you assign me ?

**Comment by Vivek-1102** [comment]
@wrussell1999 what about the font size it seems to be perfect.

**Comment by wrussell1999** [comment]
@Vivek-1102 the font weight looks good for the white but the purple looks slightly lighter. If you look at the healthcare example, they're the same weight for the white and blue font.

**Comment by Vivek-1102** [comment]
@wrussell1999 I have made both the healthcare and Retail Ecosystem of the same font size i.e. 500
 
![image](https://github.com/user-attachments/assets/2b965b10-ecaa-4f1e-8492-6611f8b3cef4)

**Comment by Vivek-1102** [comment]
@wrussell1999 am I good to go for a pull request or should I make the font size to 600, then it will differ from the healthcare example.

**Comment by wrussell1999** [comment]
Looks good! Open the PR! @Vivek-1102

**Comment by Vivek-1102** [comment]
Yes sir!
@wrussell1999 I have made my PR #1822 please have a look
