### ISSUE TITLE
Missing some Pebble expression filter and functions in the documentation

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/docs#1843]
### Description

The documentation is not exhaustive for all supported Pebble expression filter and functions.

For ex, the `endWith` filter is missing, see https://github.com/kestra-io/kestra/issues/5390

The current list of customization of the templating engine can be found here: https://github.com/kestra-io/kestra/blob/develop/core/src/main/java/io/kestra/core/runners/pebble/Extension.java

**Comment by shrutimantri** [comment]
Missing Filters
[] endsWith
[] json
[] flatten
[] toIon

Missing Functions
[] json
[] kv
[] encrypt
[] decrypt
[] fromIon
