### ISSUE TITLE
Kestra FAQ page broken

### ISSUE THREAD

**Issue by nssachin** [kestra-io/docs#1844]
### Description

Kestra FAQ page(https://kestra.io/faq) is partially broken. Tried hard refresh and multiple browsers. Attaching screenshot as a reference:
![Screenshot 2024-10-10 at 2 55 32 PM](https://github.com/user-attachments/assets/77384faa-af50-4be7-88e8-37c43bada6a0)

**Comment by wrussell1999** [comment]
I can reproduce too
![Screenshot 2024-10-10 at 10 34 17](https://github.com/user-attachments/assets/8e422b60-f9e3-46bd-89e6-e0b0fd684caa)

**Comment by Vivek-1102** [comment]
@wrussell1999 happy to contribute, please assign me the issue.

**Comment by Vivek-1102** [comment]
@wrussell1999 can you tell me what is the expected output?
