### ISSUE TITLE
Fix kestra guide in the Airbyte docs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1900]
### Description

The blueprint URLs are outdated as they use old URL format and point to the demo page because back then we didn't have blueprints on the website: https://docs.airbyte.com/operator-guides/using-kestra-plugin

The task is to fix those URLs and any other outdated information, perhaps updating also UI screenshots

![image](https://github.com/user-attachments/assets/d4c72ed2-7a3c-4538-9871-6ba75ba7b4a4)

Ofc this requires a PR to Airbyte, not here to the kestra docs repo :)

**Comment by shrutimantri** [comment]
Updated the doc: https://github.com/airbytehq/airbyte/pull/47440
UI screenshots are all gifs. The last gif has older code in the blueprint, but I am not sure how to generate such good quality gif with background and zoom effects. Can you please help me with it, or assign the gif creation to our design team?

**Comment by anna-geller** [comment]
Thanks for the PR. Don't worry about the GIF, it's totally fine without it :)

**Comment by wrussell1999** [comment]
Is there anything else that needs doing to close this? Looks done as far as I can tell

**Comment by shrutimantri** [comment]
This is done. Closing the issue.
