### ISSUE TITLE
Standardize configuration notation to use camelCase everywhere instead of hyphen-case

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1928]
### Description

The main page is already handled https://github.com/kestra-io/docs/commit/05fe69dfd5bc433580c18c95a19db67c65b6ffa7

We need to adjust other docs pages that reference configuration

**Comment by wrussell1999** [comment]
Docker Compose also updated with camelCase and tested: https://github.com/kestra-io/kestra/commit/dcc23b9c080ccc15ad406a3bc1986eaadcd8d40e
