### ISSUE TITLE
Flows API `/api/v1/flows` is marked as deprecated but still valid with a YAML body

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/docs#1944]
### Description

`/api/v1/flows` is not deprecated, only the use of a JSON body is deprecated. However, the website makes it seem the whole flow is deprecated, even if you switch the request body to YAML. @Skraye can provide additional input if required.

![Screenshot 2024-11-12 at 12 05 56](https://github.com/user-attachments/assets/246b2a44-8516-489b-93ab-b951beabaa9d)

Can we fix this messaging as users have reported this as confusing/unclear?

**Comment by Ben8t** [comment]
closing as duplicate with https://github.com/kestra-io/kestra/issues/4877
