### ISSUE TITLE
Make background color of all mermaid diagrams white or grey so that it displays correctly in dark mode

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1946]
### Describe the issue

Go to the end of the States page and expand the mermaid diagram:

![image](https://github.com/user-attachments/assets/c7b168ef-e5af-42a1-960f-58d3d736bae4)

![image](https://github.com/user-attachments/assets/48ba99c1-25aa-4ff1-8003-ca81eda65c82)

We should make the background white or grey

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by Piyush-r-bhaskar** [comment]
Hi @anna-geller ,

I can do this. Please assign.
