### ISSUE TITLE
Replace EachSequential and EachParallel with ForEach

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/docs#1947]
### Description

A few places in the docs still reference EachSequential and EachParallel / use it in examples. We need to replace these and link to ForEach instead.

Places that need fixing (but doesn't necessarily mean this is everything - add as you find stuff)
- [x] https://kestra.io/docs/best-practices/flows#task-in-the-same-execution
- [x] https://kestra.io/docs/workflow-components/outputs#specific-outputs-for-dynamic-tasks
- [x] https://kestra.io/docs/workflow-components/variables#can-i-use-nested-variables
- [x] https://kestra.io/docs/tutorial/flowable
- [x] https://kestra.io/docs/migration-guide/0.11.0/templates#templates-%EF%B8%8F
- [x] https://kestra.io/docs/concepts/namespace-files
- [ ] #1974
 are using this deprecated plugin - we should update all those plugin examples - @wrussell1999 
- [x] https://kestra.io/docs/expressions/expression-usage

(check to see if any are missing)

We also need to redo the [Flowable Page](https://kestra.io/docs/workflow-components/tasks/flowable-tasks) and remove EachParallel and EachSequential.

- [x] Replace references - @shrutimantri 
- [x] Reword [page](https://kestra.io/docs/workflow-components/tasks/flowable-tasks) - @wrussell1999

**Comment by anna-geller** [comment]
for the last one about Trigger, would be cool to take time to clean up the Trigger documentation so that it's easy to understand - see example https://github.com/kestra-io/plugin-azure/commit/35afd6348935be98bb77a03d9a7120e8b28a63fc

**Comment by wrussell1999** [comment]
@shrutimantri can you go through all of these and update to ForEach?

- https://github.com/search?q=org%3Akestra-io%20EachSequential&type=code
- https://github.com/search?q=org%3Akestra-io%20EachParallel&type=code
