### ISSUE TITLE
Improvements to docs, blueprints and search

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#2010]
## Problem

For both `blueprints` + `docs` repo, keeping `develop` + `main/latest-stable` is a bit tedious, and it is hard to keep them in sync. 

The `api` is also affected.  

We had **merge conflicts** between `develop` and the `main` branches.

Unclear to which one new people in the company needs to commit things.

E.g. if someone wants to make a change to a blueprint, they need to merge it to both develop and latest-stable.

## Next steps

- [x] Single main branch for both repos → `latest-stable` will be renamed to `main` on the `blueprints` repo and `develop` branch will be killed.
- [x] `develop` branch will also be killed on the api repo
- [x] When we push to `main` branch, it will push docs and blueprint changes to kestra develop (snapshot) and to latest stable version of kestra
- [x] we need to add a tag when we release on blueprints, api and docs repos → tag: `v0.21.x` - TODO needs to add a GitHub action to automate the process
- [x] indexing will be triggered anytime we add a tag on the blueprints and docs repos, but not on api repo → this will allow us to even fix indexing on older versions, we need to delete the version tag, cherry-pick the fix and re-add the the tag
- [x] document internally e.g. in Notion how the process works e.g. if we need to trigger indexing, document which flow in cloud needs to be triggered etc
- search on the main website docs
    - [x] is too strict when typing more than one word; it would be better if we could have a fuzzy search allowing to match broad search terms
    - [x] should index flow definition from blueprint

**Comment by brian-mulier-p** [comment]
Everything is tackled except the auto tagging CI. I created a follow-up issue [here](https://github.com/kestra-io/docs/issues/2023).
