### ISSUE TITLE
Sorts blog articles by last published instead of slug date

### ISSUE THREAD

**Issue by MartinRst** [kestra-io/docs#330]
### Issue description

When we update an article or change the date, as a user I want my article that was lastly modified with the publication date changed to be displayed first.

**Comment by anna-geller** [comment]
it works now! 🎉 

we no longer have to set any dates in the blog post URL, it's now sorted automatically by `date` set in frontmatter

![image](https://github.com/user-attachments/assets/7356b49b-15e6-4197-b489-1b55af08b679)
