### ISSUE TITLE
Documentation - Developer Guide - VSC for ext/load JSON Schema to validation YAML flow

### ISSUE THREAD

**Issue by quentin-js** [kestra-io/docs#379]
### Issue description

Following a discussion, we can improve the options to build flow outside of the Kestra UI?

Original idea is based on this message:
```
Yes, you can start a local kestra with the directory if needed, see https://kestra.io/docs/administrator-guide/servers#kestra-local-development-server-with-no-dependencies
Or use VSCode for ex and load the JSON Schema that allows to validate flow YAML (this is not documented).
I think the 3 ways to develop flows (the third being via the UI) should be documented at the root of the developer guide, you can also open an issue about that 
```

**Comment by brian-mulier-p** [comment]
Documentation about this should include the [VSCode extension](https://github.com/kestra-io/vscode-kestra/tree/main) by this time

**Comment by anna-geller** [comment]
including in bigger docs planning for easier prioritization https://www.notion.so/kestra-io/Desired-documentation-enhancements-1369a3ded29c4c8d906950cd4ac8d59e?pvs=4
