### ISSUE TITLE
Add Book a demo page

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/docs#388]
### Feature description

Develop the [Book a demo](https://www.figma.com/file/g8Di3M1gbajOjOqp0ZrzXO/Kestra.io?type=design&node-id=1417%3A8931&mode=design&t=j6Xp9aGmK9YvP1YQ-1) page
And All Links to book a demo must land on this page (header/HP/EE...)

**Comment by mageexcel** [comment]
I will do it.

**Comment by MartinRst** [comment]
Hey, this is the embed code for the form: 

`<script charset="utf-8" type="text/javascript" src="//js-eu1.hsforms.net/forms/embed/v2.js"></script>
<script>
  hbspt.forms.create({
    region: "eu1",
    portalId: "27220195",
    formId: "d8175470-14ee-454d-afc4-ce8065dee9f2"
  });
</script>`
