### ISSUE TITLE
Modify the Plugins page

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/docs#399]
### Feature description

[Figma](https://www.figma.com/file/g8Di3M1gbajOjOqp0ZrzXO/Kestra.io?type=design&node-id=3288%3A26508&mode=design&t=4c9CqrAGZscNAXHu-1)

Same template as the Blueprints pages. Initially, the plugins will redirect to the documentation.
In a second phase, we will create SEO pages with @MartinRst 

@Ben8t @anna-geller can you think about the names of the categories? (e.g., Database, Marketing Analytics, etc...)

Thanks

**Comment by anna-geller** [comment]
Possible categories:
- AWS
- Azure
- GCP
- Scheduling
- Notifications
- Data Ingestion
- Data Quality
- Storage
- Database
- Data Warehouse
- Data Lakehouse
- Message Queue
- Python
- R
- Node.js
- Kubernetes
- AI
- Git

**Comment by loicmathieu** [comment]
Categories are defined inside the plugin, the current list is here: https://github.com/kestra-io/kestra/blob/develop/core/src/main/java/io/kestra/core/models/annotations/PluginSubGroup.java#L18

```
        DATABASE,
        MESSAGING,
        SCRIPT,
        TRANSFORMATION,
        FLOW,
        BATCH,
        ALERTING,
        CLOUD,
        STORAGE,
        MISC,
        TOOL,
        AI
```

**Comment by anna-geller** [comment]
thanks @loicmathieu 👍 is it documented somewhere what each of those mean? e.g.:
1. tool and misc are confusing. 
2. Cloud could be almost anything
3. storage - is it meant for file systems and cloud object stores or any data store incl. databases?

**Comment by loicmathieu** [comment]
Not documented anywhere and yes there is limitation on category name. This can be discussed and improved later but it will be easier to do it on a separate issue as it impacts all plugins

**Comment by anna-geller** [comment]
thanks for more context, added issue here https://github.com/kestra-io/kestra/issues/2181

**Comment by anna-geller** [comment]
closing as mostly done on the plugin's homepage already - feel free to open a new issue to handle a specific change
