### ISSUE TITLE
Document sanity check flow

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/docs#411]
### Feature description

It an be good to have a sanity check flow that allows, for ex via a webhood, to periodically launch a flow on a Kestra instance to check of the instance is working and can trigger a new flow.

As this is very common, we should document how to do it with a flow example.

**Comment by anna-geller** [comment]
added first to internal doc on system flows https://www.notion.so/kestra-io/Add-a-concept-of-system-flows-a99f60d7735e42f696e0a22411696ff2?pvs=4
