### ISSUE TITLE
Add Docker in Docker (dind) troubleshooting tips

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/docs#430]
### Feature description

On some Kubernetes deloyment, using dind with our defautl Helm chart can lead to:

```
Device "ip_tables" does not exist.
ip_tables              24576  4 iptable_raw,iptable_mangle,iptable_nat,iptable_filter
modprobe: can't change directory to '/lib/modules': No such file or directory
error: attempting to run rootless dockerd but need 'kernel.unprivileged_userns_clone' (/proc/sys/kernel/unprivileged_userns_clone) set to 1
```

This can be solved by using root to launch the dind container by setting the following values:

```
dind:
  image:
    tag: dind
  args:
    - --log-level=fatal
  securityContext:
    runAsUser: 0
    runAsGroup: 0

securityContext:
  runAsUser: 0
  runAsGroup: 0
```

Alternatively to document that, we can also make it easier to configure on the Helm chart.

See https://app.slack.com/client/T01JX6XH5KN/C03FQKXRK3K/thread/C03FQKXRK3K-1691653990.092489

**Comment by anna-geller** [comment]
done in https://github.com/kestra-io/docs/commit/84fc6f36a2ec07c899fe9829c471e33d3d845be1
