### ISSUE TITLE
Integrate the Partner page

### ISSUE THREAD

**Issue by MartinRst** [kestra-io/docs#450]
### Feature description

https://www.figma.com/file/g8Di3M1gbajOjOqp0ZrzXO/Kestra.io?type=design&node-id=3422-24733&mode=design&t=7HCAbuOBgeFjNtU4-0

URL: kestra.io/partners
Title: Kestra Partner Ecosystem
Meta Description: Whether you are building something new, upgrading the existing, or replatforming from the old, you can trust these partners to make your journey a successful one.

For the form: `<script charset="utf-8" type="text/javascript" src="//js-eu1.hsforms.net/forms/embed/v2.js"></script>
<script>
  hbspt.forms.create({
    region: "eu1",
    portalId: "27220195",
    formId: "e044de55-bda2-4bb8-9e50-ed8c78b94922"
  });
</script>`

**Comment by mageexcel** [comment]
I will do it.

**Comment by tchiotludo** [comment]
done in #483
