### ISSUE TITLE
Missing RBAC documentation

### ISSUE THREAD

**Issue by quentin-js** [kestra-io/docs#458]
### Issue description

Hi,

The RBAC documentation is quite light. The only part is related to the Interface Guide: https://kestra.io/docs/user-interface-guide/12-roles

But nothing explaining in the Administrator Guide.

And it's also missing the Kestra Enterprise Edition documentation: https://kestra.io/docs/administrator-guide

Can you add more details about the kind of roles that can created? If it possible to add it programmatically and not via the UI? How to assign a default custom roles to new users? ect...

**Comment by anna-geller** [comment]
extra info: https://kestra.io/docs/user-interface-guide/10-administration#roles-page-ee 

We'll move EE to a dedicated section

for programmatic access: best via Terraform, but access via raw API calls is also possible

**Comment by anna-geller** [comment]
closing as done for now https://kestra.io/docs/kestra-editions/rbac

we'll keep iterating to improve it in Q1
