### ISSUE TITLE
Document how to trigger a flow

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/docs#472]
### Feature description

Currently, the Developer Guide didn't extensibely document how to trigger a flow.
It should document it inside the Flow page: https://kestra.io/docs/developer-guide/flow

There is some documentation inside the input page, maybe it should be moved to the flow page and extended, see https://kestra.io/docs/developer-guide/inputs#set-input-values-at-flow-execution

**Comment by loicmathieu** [comment]
Maybe adding a python example will be interesting also, see https://app.slack.com/client/T01JX6XH5KN/C03FEGF31PW

**Comment by anna-geller** [comment]
it should include the new python lib methods https://github.com/kestra-io/libs/pull/1
