### ISSUE TITLE
Replace deprecated script tasks in examples

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#474]
### Issue description

Several docs examples use Deprecated tasks, such as:
- io.kestra.core.tasks.scripts.Bash - used a lot across the Developer Guide
- io.kestra.core.tasks.scripts.Python - used in the main tutorial
- io.kestra.core.tasks.debugs.Echo

We should switch these for non-deprecated alternatives such as:
- io.kestra.plugin.scripts.shell.Commands
- io.kestra.plugin.scripts.python.Script
- io.kestra.core.tasks.log.Log

It might be done after the new Editor e.g. in release 0.13.0 in case Script tasks are no longer as necessary (can use Commands with local scripts)

**Comment by loicmathieu** [comment]
io.kestra.core.tasks.log.Log should be used instead of io.kestra.core.tasks.debugs.Echo
