### ISSUE TITLE
Header: Add GitHub stars count

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/docs#477]
### Feature description

Need to have github stars count on the header
<img width="517" alt="Capture d’écran 2023-09-01 à 14 49 31" src="https://github.com/kestra-io/docs/assets/125994028/a257a184-36ac-4e1f-9a77-1e81ef6aa7f6">

[Figma](https://www.figma.com/file/g8Di3M1gbajOjOqp0ZrzXO/Kestra.io?type=design&node-id=249%3A372&mode=design&t=mXUsAWEZ1gHlKN7j-1)

**Comment by Nico-Kestra** [comment]
Up!

**Comment by tchiotludo** [comment]
outdated
