### ISSUE TITLE
Issues on Partners page

### ISSUE THREAD

**Issue by MartinRst** [kestra-io/docs#494]
The CTAs to join the partners' program are redirecting to nothing + related to the ticket=> https://github.com/kestra-io/docs/issues/450  the CTA needs to be the embedded one and not an API one

Embed code: 

`<script charset="utf-8" type="text/javascript" src="//js-eu1.hsforms.net/forms/embed/v2.js"></script>
<script>
  hbspt.forms.create({
    region: "eu1",
    portalId: "27220195",
    formId: "e044de55-bda2-4bb8-9e50-ed8c78b94922"
  });
</script>`

The CTAs on the cards need to be anchored to the form at the page's bottom

No <title> and no <meta_description> tags.

Title:  Kestra Partner Ecosystem
Description: A list of consulting or technology partners you can trust when using Kestra

**Comment by tchiotludo** [comment]
fix in https://github.com/kestra-io/docs/commit/904455f9d8ae4292e8ed1abad21f2992725a6c07
