### ISSUE TITLE
Cassandra & DataStax's AstraDB (managed Cassandra) should be in different sections in the docs

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/docs#499]
in the site: 
![image](https://github.com/kestra-io/docs/assets/2064609/3168f402-1d2e-4812-9e37-a7902b7e1aae)

in the app: 
![image](https://github.com/kestra-io/docs/assets/2064609/bafe8027-fa71-4086-b9bd-3f3374014975)

**Comment by anna-geller** [comment]
![image](https://github.com/kestra-io/docs/assets/86264395/66f5c2e0-5800-4bc7-9313-a140c56fe295)
