### ISSUE TITLE
Add external blog post page in Kestra's blog

### ISSUE THREAD

**Issue by MartinRst** [kestra-io/docs#501]
### Feature description

Add the possibility of sharing external news in [Kestra's blog](https://kestra.io) related to this Figma files: 
<img width="841" alt="image" src="https://github.com/kestra-io/docs/assets/125883179/0840a71e-fe3f-4f69-a30d-c14997d1f1bd">

How it should work for this page: https://www.figma.com/file/g8Di3M1gbajOjOqp0ZrzXO/Kestra.io?type=design&node-id=3207-22826&mode=design&t=r00uX0E7eNFH0gYB-0

The left part needs to be managed as it is right now. it's the /blogs/ slug but with an added component on the right:

The part about "Last Community’s News" is external content we need to manage: the link, the image the title, author, Source of the article) date.

For this page: https://www.figma.com/file/g8Di3M1gbajOjOqp0ZrzXO/Kestra.io?type=design&node-id=3235-21540&mode=design&t=r00uX0E7eNFH0gYB-0

It needs to be in the SLUG: kestra.io/blogs/community/It's an index of the external links, same here we need to manage the content information: Title, Source ,author, date.

IMPORTANT NOTE: THEY SHOULD NOT BE MIXED WITH THE INTERNAL CONTENT FROM THE BLOG.

Next step: When the component are ready let me know so I can add the real contents instead of placeholders.

**Comment by tchiotludo** [comment]
done in https://github.com/kestra-io/docs/pull/579
