### ISSUE TITLE
Add A terraform Provider Page

### ISSUE THREAD

**Issue by MartinRst** [kestra-io/docs#528]
### Feature description

**Title for the page**:  Kestra Terraform Provider: Deploy All Your Workflows in a CI/CD Process

**Description**: Manage and deploy Kestra workflows directly within your existing Terraform environment, eliminating the need for separate configurations. 

URL: https://kestra.io/terraform-provider

The hyperlink in the text are available in comment on the Figma

https://www.figma.com/file/g8Di3M1gbajOjOqp0ZrzXO/Kestra.io?type=design&node-id=4323-22127&mode=design&t=14URZZhf8dZH1QGZ-0

<img width="367" alt="image" src="https://github.com/kestra-io/docs/assets/125883179/2d3b8b14-1090-4d3d-9e12-3936ad2fbba8">

**Comment by anna-geller** [comment]
done in https://kestra.io/use-cases/terraform-provider 

Martin please reopen if you meant a different page
