### ISSUE TITLE
EE plugins don't render properly in the docs - remove them from the docs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#612]
AWS Secret:
- https://kestra.io/plugins/secret-aws shows the task
- https://kestra.io/plugins/secret-aws/secrets/io.kestra.ee.secret.aws.awssecret broken link

Same for Azure:
- https://kestra.io/plugins/secret-azure works
- https://kestra.io/plugins/secret-aws/secrets/io.kestra.ee.secret.aws.awssecret doesn't work

And GCP
- https://kestra.io/plugins/secret-googlecloud
- https://kestra.io/plugins/secret-googlecloud/secrets/loud/io.kestra.ee.secret.googlecloud.googlecloudsecret

And for Vault:
- https://kestra.io/plugins/secret-vault -- here the extra mistake is that someone forgot to rename the plugin :) it's still named as Template 
- https://kestra.io/plugins/secret-vault/secrets/io.kestra.ee.secret.vault.vaultsecret

**Comment by tchiotludo** [comment]
Already fixed
