### ISSUE TITLE
Create the Retail page

### ISSUE THREAD

**Issue by MartinRst** [kestra-io/docs#644]
### Feature description

Slug: https://kestra.io/use-cases/retail/
Title: Kestra for Retail and Consuming goods
Description: From data pipelines to complex integrations, Kestra empowers retail businesses with an event-driven, language-agnostic orchestration platform that scales as you grow.

Figma Link: https://www.figma.com/file/g8Di3M1gbajOjOqp0ZrzXO/Kestra.io?type=design&node-id=5729-3827&mode=desig
![Retail (2)](https://github.com/kestra-io/docs/assets/125883179/eb0212b3-9bbf-45a9-aed0-3b3cd07d5641)
n&t=0sZHWl9bv1dKBlif-0

**Comment by ridge-kimani** [comment]
@MartinRst Could you provide the raw files for the icons and images?
