### ISSUE TITLE
Issues with the background of Customer Stories header background

### ISSUE THREAD

**Issue by MartinRst** [kestra-io/docs#665]
Issues on all headers with the wrong color background: 

https://kestra.io/use-cases/stories/orlando-city-sc

<img width="1261" alt="image" src="https://github.com/kestra-io/docs/assets/125883179/19a82680-5bb2-49c4-bb76-9fe18b448d30">

**Comment by ridge-kimani** [comment]
I confirmed this is working correctly in the current build.

**Comment by MartinRst** [comment]
Yes corrected! closing the issue
