### ISSUE TITLE
Image size on the documentation

### ISSUE THREAD

**Issue by MartinRst** [kestra-io/docs#666]
With the new display of the documentation the images are looking very small: 

For example https://kestra.io/docs: 
<img width="625" alt="image" src="https://github.com/kestra-io/docs/assets/125883179/f2f8eeda-2e46-4d98-a27e-658d07540745">

It should take the same size as in the blog:

<img width="838" alt="image" src="https://github.com/kestra-io/docs/assets/125883179/3db04925-d259-4ef0-8815-8379d4b24ef4">

**Comment by rldorado** [comment]
Reopened as my PR created another issue and had to reverse. I'm thinking another way to solve this.

https://github.com/kestra-io/docs/pull/675

**Comment by rldorado** [comment]
This issue has been already solved by this PR: https://github.com/kestra-io/docs/pull/672

Closing this issue.
