### ISSUE TITLE
[UI] Add dark mode for docs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#678]
### Feature description

I know @Nico-Kestra already created the design: https://www.figma.com/file/g8Di3M1gbajOjOqp0ZrzXO/Kestra.io?type=design&node-id=5959%3A35739&mode=design&t=u9tcGoTtjDeVeGJ8-1 

![Kestra-Docs (1)](https://github.com/kestra-io/docs/assets/86264395/bd8c6ea0-a193-4e71-a186-41bae546cdd6)

**Comment by anna-geller** [comment]
test comment

**Comment by ridge-kimani** [comment]
Will there be a toggle for the modes or it depends on the system's default?

**Comment by ridge-kimani** [comment]
NV. Just saw it.

**Comment by ridge-kimani** [comment]
Is it possible to have the toggle on the navbar, maybe top-right?

**Comment by anna-geller** [comment]
Hi Ridge, thanks so much for your interest in contributing to this page. This one will be difficult as it needs a website dark mode to be added first to avoid overwriting global styles. We will have only dark mode for both the website and docs.

Meanwhile, if you are looking to contribute, perhaps you can check this issue? https://github.com/kestra-io/docs/issues/688

**Comment by ridge-kimani** [comment]
Yeah, sure. I will check it out. Thanks.
