### ISSUE TITLE
Create the write for Kestra page

### ISSUE THREAD

**Issue by MartinRst** [kestra-io/docs#688]
### Feature description

This is the write for Kestra page, the CTA will be a form from hubspot hyperlink:
![Write for the kestra Community](https://github.com/kestra-io/docs/assets/125883179/67a3e6cd-4762-466b-ba5e-26b808d9af49)

https://www.figma.com/file/g8Di3M1gbajOjOqp0ZrzXO/Kestra.io?type=design&node-id=6530-37296&mode=design&t=TIP2aOKLxvRT801D-0

**Slug of the page**: https://kestra.io/write-for-kestra/
**Meta Title**: Write for the Kestra Community
**Meta Description**: If you are a software engineer, or tech enthusiast passionate about orchestration, scheduling, and workflow automation, we at Kestra are inviting you to share your knowledge and insights by writing for us.

Dropdown content of the FAQ:
FAQs

**Compensation**: Original articles are compensated at a competitive rate (exact amount to be specified), payable upon publication.
**Cross-Posting**: You can cross-post your article on other platforms, provided a canonical link to the Kestra site is included.

**Comment by ridge-kimani** [comment]
Picking this up

**Comment by ridge-kimani** [comment]
Could you share the Figma doc too for any assets and other stylings?
