### ISSUE TITLE
[Fix]: alignment in the community news sidebar

### ISSUE THREAD

**Issue by ridge-kimani** [kestra-io/docs#735]
### Expected Behavior

The sidebar in the blogs page that contains community news needs to be right aligned.

### Actual Behaviour

The sidebar is not aligned perfectly with the navbar
![Screenshot 2024-01-02 at 10 42](https://github.com/kestra-io/docs/assets/101694484/f8652fb3-0b5d-4d77-9fc5-9d294845b2db)

### Steps To Reproduce

On the docs page, navigate to `/blogs`

### Environment Information

- Docs version: latest

**Comment by anna-geller** [comment]
do you mean right-aligned?

**Comment by ridge-kimani** [comment]
Sure @anna-geller, thanks!
