### ISSUE TITLE
Generate sitemap for strapi content

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/docs#741]
Since we are using a lot strapi, we need to generate a sitemap to index them easily. 

At first, we need one for: 
- [Blueprints](https://kestra.io/blueprints)
- [Customer Stories](https://kestra.io/use-cases/stories)
- All plugins (after this https://github.com/kestra-io/docs/pull/711) 

We need to: 
- Create a separate one by type 
- make it easy to add new one

**Comment by brian-mulier-p** [comment]
#766 was also part of it
