### ISSUE TITLE
Handle missing icon

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/docs#743]
![image](https://github.com/kestra-io/docs/assets/2064609/10c15c05-3788-4205-8898-bb11a619e927)

see here : https://kestra.io/icons/io.kestra.plugin.jdbc.druid.Query.svg

Use the default icon, kept the 404 response code

**Comment by anna-geller** [comment]
I tried here but can't test locally https://github.com/kestra-io/plugin-jdbc/commit/1c43c8581a6ca56aa52f3b5cc0c1071be6dd14f1

**Comment by anna-geller** [comment]
ok still not working

**Comment by Skraye** [comment]
fix by https://github.com/kestra-io/plugin-jdbc/commit/f733bc988b46a293e0a98fece8e8427c79f8174f
Missing icons folders
