### ISSUE TITLE
Redirect demo.kestra.io to https://us.kestra.cloud/ui/demo/dashboard

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#761]
### Feature description

Redirect to https://us.kestra.cloud/ui/demo/dashboard 
```[tasklist]
### Tasks
- [ ] After the redirect is implemented, replace any demo.kestra.io mention by the Cloud link
```

**Comment by tchiotludo** [comment]
done, we kept the demo.kestra.io for convenience, but maybe kestra.io/demo will be better ?

**Comment by anna-geller** [comment]
https://kestra.io/demo is for booking a call with David, so better not to get those confused :D 

demo.kestra.io works, great to see redirect works already 👍
