### ISSUE TITLE
Docs: Move the Icon plugin front of the title.

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/docs#768]
### Expected Behavior

The icon is wandering in the middle of the page, please place it in front of the title.
<img width="781" alt="Capture d’écran 2024-01-10 à 13 49 43" src="https://github.com/kestra-io/docs/assets/125994028/5a9baa6b-b2af-465a-b12d-604dafd56fe8">

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by anna-geller** [comment]
Nico, I'll close this issue as soon this page will look the same way it does in your new design https://kestra-io-git-fix-plugins-hp-kestra.vercel.app/plugins 

we already have a PR https://github.com/kestra-io/docs/pull/762

**Comment by Nico-Kestra** [comment]
I don't understand, we're not talking about the same thing. For me, it's the issue of icons in the middle of the content.

**Comment by anna-geller** [comment]
I'm sorry, you're totally right, the detail page of a plugin still shows it, well spotted thanks for the issue Nico! https://kestra-io-git-fix-plugins-hp-kestra.vercel.app/plugins/core
