### ISSUE TITLE
Breadcrumb on plugins tasks don't show plugin in breadcrumb

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/docs#823]
### Actual Behaviour

Probably a regression from plugins page reworks

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by anna-geller** [comment]
Seems done by now, we can now click on the parent plugin group by following the breadcrumb 

![image](https://github.com/user-attachments/assets/57c5b420-d87f-4928-b8d5-a05adbdb090c)
