### ISSUE TITLE
Blog on mobile have issue with responsiveness

### ISSUE THREAD

**Issue by MartinRst** [kestra-io/docs#845]
### Issue description

Hey! See the video below the content is cut on the right on mobile view for the blog: 

https://github.com/kestra-io/docs/assets/125883179/6f4fd427-f3a6-4912-813a-89563138fc88

**Comment by brian-mulier-p** [comment]
fixed by https://github.com/kestra-io/docs/commit/8f5ba01e485545eab5f5d48cc9d21d1903d51fec
