### ISSUE TITLE
Incoherent URLs in plugin documentation section

### ISSUE THREAD

**Issue by kriko** [kestra-io/docs#862]
### Issue description

Slightly strangely, depending upon where you move to a plugin's documentation you will get 2 different type URLs:

For example:
1. https://kestra.io/plugins/plugin-git/tasks/io.kestra.plugin.git.Sync
2. https://kestra.io/plugins/tasks/io.kestra.plugin.git.Sync

The content appears to be the same, however there is a slight difference in the breadcrumbs: 
1. [plugins](https://kestra.io/plugins) > [plugin-git](https://kestra.io/plugins/plugin-git) > tasks > [io.kestra.plugin.git.Sync](https://kestra.io/plugins/plugin-git/tasks/io.kestra.plugin.git.Sync) - where plugin-git itself is a hyperlink
2. [plugins](https://kestra.io/plugins) > tasks > io.kestra.plugin.git.Sync - where the breadcrumb only has a link to plugins

When correcting ensure that old links work (eg using a HTTP redirect 301 Moved Permanently).

**Comment by anna-geller** [comment]
sorry we get to it late; depending on whether you navigate to the task docs from kestra.io/plugins or from the plugin's page, the breadcrumb looks a bit differently but the content works as expected and both links work, so we'll close the issue
