### ISSUE TITLE
Specify software requirements

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/docs#868]
### Feature description

Common deployments require multiple 3rd party software components. Currently, the docs rarely specify the minimal compatible versions (nor recommended vendor) of those software components.

Admins deploying the OSS version can inspect the [docker-compose.yml](https://github.com/kestra-io/kestra/blob/8443b81517e37183395906605a5851dfacdf9a46/docker-compose.yml) file but there is no alternative for the EE deployments.

An example of easily comprehensible aggregation of Kestra software requirements follows:

| Component  | Required version | Note |
| ------------- | ------------- | --------|
| **Java JDK** | 17-21? | _tested with Eclipse Temurin_ |
| **MySQL**  | x.y.z with exception 8.0.31  | |
| **PostgreSQL**  | 14 or newer | |
| **MinIO**  | x.y.z or newer | |
| **Apache Kafka**  | x.y.z | |
| **Elasticsearch**  | x.y.z up to a.b.c | _alternatively OpenSearch x.y.x or newer_ |
| **OpenSearch**  | x.y.z or newer | _alternatively Elasticsearch x.y.z up to a.b.c_ |

Related to hardware requirements #363

**Comment by anna-geller** [comment]
great idea!
