### ISSUE TITLE
Google result leads to 404 page, search within produces a result but fails to open the correct page

### ISSUE THREAD

**Issue by kriko** [kestra-io/docs#871]
### Expected Behavior

On the 404 page, using search should work and lead to the correct page.

Ideally, changed links from the previous documentation should be redirected to their respective locations in the new documentation.

### Steps To Reproduce

1. Google "[kestra first](https://www.google.com/search?q=kestra+first&oq=kestra+first)"
2. First result leads to the old JSON filter page at: https://kestra.io/docs/concepts/expression/filter/first
3. Page renders as 404 after documentation was upgraded.
4. Use Kestra website search to search for eg "first" to find the JSON filter.
5. Click on the search result, nothing happens.

### Environment Information

- Browser: Google Chrome
- Browser: Firefox
- OS: MacOS

**Comment by anna-geller** [comment]
thanks so much 🙏 

fixed: https://kestra.io/docs/concepts/expression/filter/first should now redirect to https://kestra.io/docs/concepts/expression/filter
