### ISSUE TITLE
Documentation Rollout Deployment on K8S 

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/docs#903]
### Feature description

> Every service can be rollout without any downtime except worker that need a special attention.
> Standard component during the rollout will create a pod with a new version (keeping the old one running), when the pod is healthy, kubernetes will shutdown the previous one, no downtime.
> The worker is more complex since it handle some task that could vary from few secondes to hours. You need to defined the behavior for these tasks.
> By default, kestra worker process will wait till the end of all tasks running before shutting down.
> On the [helm charts](https://github.com/kestra-io/helm-charts/blob/1f9a97331ff0c160a32ceba3f255a58e01f5ff95/charts/kestra/values.yaml#L80) provided by Kestra, we configure a default terminationGracePeriodSeconds (60 secondes) that will allow to define the amount time you want to wait before force killing the worker.
> If the worker is able to terminate all the task before the grace period, it will be shutdown directly (meaning that a worker with no task will be shutdown directly).
> If the pod is not able to finished the tasks affected before  terminationGracePeriodSeconds kubernetes will kill the pod, meaning an incompleted tasks.
> In Kestra, every worker that died unexpectedly will be detected by the executor, all the tasks running will be resubmitted and handle by a new worker.  In case of rollout with terminationGracePeriodSeconds , we are in the case of unexpected failure and the task will be also resubmitted.

**Comment by anna-geller** [comment]
done on friday https://github.com/kestra-io/docs/commit/4e1e8f156a1e7916c849a65635e91438be4c816f
