### ISSUE TITLE
Documentation for upcoming input type: SECRET feature

### ISSUE THREAD

**Issue by kriko** [kestra-io/docs#917]
### Issue description

Just a friendly reminder to update the documentation with the SECRET input type that will be introduced with 0.15.0.
Feature was introduced in: [PR 2077](https://github.com/kestra-io/kestra/pull/2077)

Was able to get it working already from the snapshot, but had to figure out some details of implementation, to share:

Kestra application configuration must be extended with the following:
```
kestra:
  encryption:
    secret-key: RANDOMLY_GENERATED_STRING_OF_32_CHARCTERS
```
It seems that the key is enforced to be excatly 32 characters long.

An example can be seen in the codebase: https://github.com/kestra-io/kestra/blob/b88e96848179ba6ca0bfbba0e5b4767426f29fca/core/src/test/resources/application-test.yml#L9

PS: consider if Helm charts, docker-compose files may also require enhancement.

**Comment by anna-geller** [comment]
thx for the reminder, I will add to the release PR https://github.com/kestra-io/docs/pull/897 

the helm/docker compose all have `configuration` placeholder so you can add any configuration there incl. this one: https://github.com/kestra-io/helm-charts/blob/master/charts/kestra/values.yaml#L11 👍
