### ISSUE TITLE
[New website] Clicking on the main image on the OSS page returns a blank screen

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#921]
See in the video https://share.descript.com/view/jVV5wf3Kahm 

click on the main image to reproduce 
![image](https://github.com/kestra-io/docs/assets/86264395/78045cfd-20fc-407c-b68d-b88f0d26ac68)

**Comment by tchiotludo** [comment]
done in 44a593442a87c687eebeb3bba68f375b0fcaab90
