### ISSUE TITLE
Review EE page

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/docs#939]
### Feature description
![Kestra_EE](https://github.com/kestra-io/docs/assets/125994028/a82c50f2-e16d-4bbb-9b1a-47dc5b2d2f88)

The major changes:

- Addition of key figures
- Visual and text changes
- Removal of comparison table
- Addition of 3 feature boxes
- Screen carousel
- Highlighted customer stories area

https://www.figma.com/file/g8Di3M1gbajOjOqp0ZrzXO/Kestra.io?type=design&node-id=8189%3A15090&mode=design&t=R12NwjjlnXVBzuKg-1

**Comment by MartinRst** [comment]
Completed in https://github.com/kestra-io/docs/pull/997
