### ISSUE TITLE
Add a quotation mark inside the testimonials boxes.

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/docs#954]
### Feature description

<img width="1584" alt="Capture d’écran 2024-02-28 à 13 56 53" src="https://github.com/kestra-io/docs/assets/125994028/52a4cd3d-9582-4dee-bafa-2c7436adba7f">

https://www.figma.com/file/g8Di3M1gbajOjOqp0ZrzXO/Kestra.io?type=design&node-id=5263%3A29001&mode=design&t=HkIkKw82oP0oxDxR-1

@t-chatoyan

**Comment by t-chatoyan** [comment]
[982](https://github.com/kestra-io/docs/pull/982)
