### ISSUE TITLE
Homepage Timeline: Center the images relative to the text.

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/docs#956]
### Expected Behavior

- [ ] Can you center the images with the text?
<img width="1336" alt="Capture d’écran 2024-02-28 à 15 08 44" src="https://github.com/kestra-io/docs/assets/125994028/108b489d-e6bb-466d-bf7f-cd3fbb9fc7b3">
<img width="1147" alt="Capture d’écran 2024-02-28 à 15 08 39" src="https://github.com/kestra-io/docs/assets/125994028/c05ca0ac-5244-410a-81ba-4a6adab92cf6">

- [ ] And add a blue glue behind the box code

<img width="888" alt="Capture d’écran 2024-02-28 à 15 10 48" src="https://github.com/kestra-io/docs/assets/125994028/7b941274-6fe9-4d96-8288-3f4d1bf68468">

- [ ] Add a feedback when clicking on the copy button.
<img width="749" alt="Capture d’écran 2024-02-28 à 15 13 06" src="https://github.com/kestra-io/docs/assets/125994028/27981f72-39d4-48be-a2da-d7653664e93f">

@t-chatoyan 

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by t-chatoyan** [comment]
#989
