### ISSUE TITLE
Fix spacing and nesting of headers in the Table of Contents on the blog and docs pages

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#960]
### Feature description

![image](https://github.com/kestra-io/docs/assets/86264395/cf3a3b08-6d5c-412c-bc7f-e8fd3de08b50)

![image](https://github.com/kestra-io/docs/assets/86264395/284eb777-372f-4192-86e7-846e0bd12535)

**Comment by Nico-Kestra** [comment]
Perhaps revisiting this version:
<img width="1851" alt="Capture d’écran 2024-03-01 à 10 43 59" src="https://github.com/kestra-io/docs/assets/125994028/1f153670-6f19-4aa8-a33a-544ad7eba6b8">
The new version does not achieve consensus.

**Comment by t-chatoyan** [comment]
#995
