### ISSUE TITLE
Reduce the width of the company container on the pricing page.

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/docs#962]
### Expected Behavior

Make it the same as on the homepage.
<img width="1599" alt="Capture d’écran 2024-02-29 à 10 45 52" src="https://github.com/kestra-io/docs/assets/125994028/1ba3fd51-0ca0-4455-8207-03be44403367">

### Actual Behaviour

https://kestra.io/pricing
<img width="1971" alt="Capture d’écran 2024-02-29 à 10 46 10" src="https://github.com/kestra-io/docs/assets/125994028/9dd28e11-0da1-4c24-80df-d9b8404338dd">

@t-chatoyan

**Comment by t-chatoyan** [comment]
[974](https://github.com/kestra-io/docs/pull/974)
