### ISSUE TITLE
Blog: The main visual doesn't take up the full width.

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/docs#963]
### Expected Behavior

The visual should take up the entire width.
<img width="1180" alt="Capture d’écran 2024-02-29 à 10 57 50" src="https://github.com/kestra-io/docs/assets/125994028/03c3c350-b863-4805-b04d-47d07d2fec10">

### Actual Behaviour

The visual doesn't take up the width.
<img width="1519" alt="Capture d’écran 2024-02-29 à 10 56 13" src="https://github.com/kestra-io/docs/assets/125994028/c6835e6a-5669-4c2f-9225-909646fa7ce0">

### Environment Information

- chrome mac
- Safari mac
- Firefox

**Comment by t-chatoyan** [comment]
[977](https://github.com/kestra-io/docs/pull/977)

**Comment by MartinRst** [comment]
Completed in https://github.com/kestra-io/docs/pull/977
