### ISSUE TITLE
Reduce the size of the feature boxes on mobile.

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/docs#964]
### Expected Behavior

Please revise these feature boxes to make them smaller, with titles centered vertically alongside the icons.
![Homepage](https://github.com/kestra-io/docs/assets/125994028/ec1bc9fa-2e4d-41f5-a08f-19a73b76195e)

https://www.figma.com/file/g8Di3M1gbajOjOqp0ZrzXO/Kestra.io?type=design&node-id=9310%3A42202&mode=design&t=SfofqD9ujJtLmInT-1

### Actual Behaviour

<img width="456" alt="Capture d’écran 2024-02-29 à 11 08 33" src="https://github.com/kestra-io/docs/assets/125994028/d1a6689b-6a78-49ac-a143-9cb5a4616f6c">

@t-chatoyan

**Comment by t-chatoyan** [comment]
[973](https://github.com/kestra-io/docs/pull/973)

**Comment by Nico-Kestra** [comment]
<img width="449" alt="Capture d’écran 2024-03-01 à 09 21 37" src="https://github.com/kestra-io/docs/assets/125994028/6eeac24f-938c-471a-a367-d1126b0472c8">
Could you please reduce the spacing between the boxes to 16px? Then we'll be all set. Thank you!

**Comment by t-chatoyan** [comment]
#996
