### ISSUE TITLE
Plugin Documentation: Move Position Icon Plugin

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/docs#966]
### Expected Behavior

Could you position the plugin icon here? It doesn't make sense for it to be in the middle. Thank you.
<img width="1081" alt="Capture d’écran 2024-02-29 à 14 25 36" src="https://github.com/kestra-io/docs/assets/125994028/84308009-9d62-48bb-bc54-0849172b77b2">

### Actual Behaviour

<img width="800" alt="Capture d’écran 2024-02-29 à 14 28 08" src="https://github.com/kestra-io/docs/assets/125994028/7928a7ee-0398-4170-a51d-a4510be60cd7">

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by t-chatoyan** [comment]
@Nico-Kestra I am getting this list from backend need to change it in backend

**Comment by Nico-Kestra** [comment]
@tchiotludo

**Comment by tchiotludo** [comment]
you should use css to hide the invalid icon and add manually the icon

**Comment by t-chatoyan** [comment]
I think we can't add icon via css in MD
