### ISSUE TITLE
Fix social cards for main pages that include animation

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#976]
### Feature description

example https://twitter.com/anna__geller/status/1763489902396596349?t=OcuCXR8oWyrddwry3PYAtA&s=19

![image](https://github.com/kestra-io/docs/assets/86264395/25fc63fa-483e-4957-a674-1b24924c2b5e)

**Comment by t-chatoyan** [comment]
@anna-geller I don't see animation in the example please can you show me with video ?

**Comment by anna-geller** [comment]
sure https://share.descript.com/view/ewwRr3789cG

**Comment by anna-geller** [comment]
still the case today even though we no longer have that animation on the website - @t-chatoyan in case you know how to fix this

![image](https://github.com/user-attachments/assets/2142f4e8-069e-4644-a8fe-95d8fd611ebf)

**Comment by anna-geller** [comment]
done https://github.com/kestra-io/docs/pull/1616
