### ISSUE TITLE
Change API reference text color to white 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#978]
### Feature description

![image](https://github.com/kestra-io/docs/assets/86264395/feaaba56-6315-45ca-8b65-9fb8b2c62b73)

**Comment by Nico-Kestra** [comment]
Would this early draft help you?
<img width="1861" alt="Capture d’écran 2024-03-01 à 11 56 57" src="https://github.com/kestra-io/docs/assets/125994028/f4f8cd64-6966-470f-a29b-8e824b0d57d7">
https://www.figma.com/file/g8Di3M1gbajOjOqp0ZrzXO/Kestra.io?type=design&node-id=9370%3A43084&mode=design&t=yMzyupfCK2rGU4aY-1

**Comment by anna-geller** [comment]
seems fixed now 

![image](https://github.com/kestra-io/docs/assets/86264395/d69ac807-09af-4e57-afdd-8a6ef677a279)
