### ISSUE TITLE
Body content is scrollable below the opened mobile menu

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/docs#991]
### Expected Behavior

I would expect that I can not move the main content of the page below by scrolling through the items of the opened mobile main menu.

### Actual Behaviour

When using the [website](https://kestra.io/) of the company on mobile devices (or any smaller screen) and open the main menu, after scrolling to the bottom of the list of items in it (currently that's a GH stars counter followed by three block buttons at the very end) the entire content of the page behind it can be seen moving around if we continue to scroll some more.

I'm not completely sure if this behaviour is like that by design, but it felt kinda weird so I'm raising this issue (to go along with a PR which will resolve it).

### Steps To Reproduce

1. Open official [website](https://kestra.io/) on mobile device (or on any screen, but resize browser window to see mobile menu).
2. Open mobile menu by clicking the button in the top header.
3. Scroll down to see the GH stars counter with the three buttons at the very bottom.
4. Continue scrolling in the same direction and see that the main page content is being moved.
5. *Be a bit confused whether that is the expected behaviour.

\* Not required 🙂 

### Environment Information

Production website of the company at https://kestra.io/.

**Comment by Nico-Kestra** [comment]
Hello @MilosPaunovic ,
I have the impression that this is due to the transparency behind the menu, and we can see the enterprise logos scrolling. We have a [issue](https://github.com/kestra-io/docs/issues/940) on the menu side to review it and remove this transparency, as well as completely revamp the menu. Additionally, we have encountered a bug: we are required to keep our finger held up to access the button section at the end.

**Comment by MilosPaunovic** [comment]
Ahh, I see. Okay, you've now cleared things up for me @Nico-Kestra, so we can close this as well as the PR. Do you want me to do it or are you going to?

Or, if you want to go in another direction, I can take a look at that additional bug, amend it and have this as a temporary solution until the menu revamp is done. It's up to you 🙂

**Comment by brian-mulier-p** [comment]
Hello ! As the menu will be revamped I feel adding a hack isn't worth it. Still thank's for the contribution @MilosPaunovic, be sure we'll make sure the issue is not there once the revamped has been done.
